Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2024-07, with the labels that each got.

#1532 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: translation

#1535 Add missing translations strings
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
Labels: translation

#1551 Added support for Thai language
  src/main/resources/messages_th_TH.properties
  src/main/resources/static/images/flags/th.svg
  src/main/resources/templates/fragments/languages.html
Labels: Front End, translation

#1555 adds Thai to the languages ​​table
  README.md
  scripts/ignore_translation.toml
Labels: documentation

#1550 version bump, multi file fix and disable survey
  build.gradle
  chart/stirling-pdf/Chart.yaml
  cucumber/exampleFiles/ghost1.pdf
  cucumber/exampleFiles/ghost2.pdf
  cucumber/exampleFiles/ghost3.pdf
  cucumber/exampleFiles/images.pdf
  cucumber/exampleFiles/pdfa1.pdf
  cucumber/exampleFiles/pdfa2.pdf
  cucumber/features/environment.py
  cucumber/features/examples.feature
  cucumber/features/external.feature
  cucumber/features/general.feature
  cucumber/features/steps/step_definitions.py
  exampleYmlFiles/docker-compose-latest.yml
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/resources/templates/convert/pdf-to-presentation.html
  src/main/resources/templates/convert/pdf-to-word.html
  src/main/resources/templates/home.html
  src/main/resources/templates/remove-pages.html
  src/main/resources/templates/security/add-watermark.html
  test.sh
Labels: java, Front End

#1559 Adding declaration as repository component & changing primary key type
  src/main/java/stirling/software/SPDF/repository/AuthorityRepository.java
  src/main/java/stirling/software/SPDF/repository/PersistentLoginRepository.java
  src/main/java/stirling/software/SPDF/repository/UserRepository.java
Labels: java

#1578 minor changes in the DEV tools and more
  .github/labeler-config.yml
  .github/scripts/check_tabulator.py
  .github/workflows/auto-labeler.yml
  .github/workflows/sync_files.yml
  build.gradle
  src/main/java/stirling/software/SPDF/config/security/database/DatabaseBackupHelper.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
Labels: Java

#1585 remove new lines and obsolete spaces
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
Labels: Translation

#1586 Update of what was missing in messages_es_ES.properties
  src/main/resources/messages_es_ES.properties
Labels: Translation

#1588 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation

#1591 Translate to Vietnamese
  scripts/ignore_translation.toml
  src/main/resources/messages_vi_VN.properties
  src/main/resources/static/images/flags/vn.svg
  src/main/resources/templates/fragments/languages.html
Labels: Documentation, Front End, Translation

#1600 Add: Vietnam to the table
  .github/labeler-config.yml
  README.md
  scripts/ignore_translation.toml
Labels: Documentation

#1599 Update messages_zh_CN.properties
  src/main/resources/messages_zh_CN.properties
Labels: Translation

#1609 Refactored Identifiers
  src/main/java/stirling/software/SPDF/SPdfApplication.java
  src/main/java/stirling/software/SPDF/config/CleanUrlInterceptor.java
Labels: Java

#1606 Danish language
  src/main/resources/messages_da_DK.properties
  src/main/resources/static/images/flags/dk.svg
  src/main/resources/templates/fragments/languages.html
Labels: Front End, Translation
