Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2024-09, with the labels that each got.

#1784 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation

#1793 Validates the file name
  src/main/java/stirling/software/SPDF/config/security/database/DatabaseBackupHelper.java
Labels: Java, Back End, Security

#1786 Feature: Split PDFs by Chapters/Bookmarks
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
  src/main/java/stirling/software/SPDF/model/api/SplitPdfByChaptersRequest.java
Labels: Java, API

#1791 Add info translation
  .github/pull_request_template.md
  HowToAddNewLanguage.md
Labels: Documentation, Github

#1809 Fix insertFileButton referencing the old addPdfs method.
  src/main/resources/static/js/multitool/PdfActionsManager.js
Labels: Front End

#1814 test
  src/main/resources/messages_da_DK.properties
Labels: Translation

#1820 Update messages_sv_SE.properties
  src/main/resources/messages_sv_SE.properties
Labels: Translation

#1822 Update messages_ro_RO.properties
  src/main/resources/messages_ro_RO.properties
Labels: Translation

#1825 Update messages_ar_AR.properties
  src/main/resources/messages_ar_AR.properties
Labels: Translation

#1808 Add document splitting functionality to the multi-tools page
  src/main/resources/static/css/multi-tool.css
  src/main/resources/static/css/pdfActions.css
  src/main/resources/static/js/multitool/PdfActionsManager.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/templates/multi-tool.html
Labels: Front End

#1836 [Bug Fix] Multiple Bug Fixes
  src/main/resources/static/js/multitool/PdfActionsManager.js
  src/main/resources/static/js/multitool/PdfContainer.js
Labels: Front End

#1837 [Bug Fix] Fix Firefox Page Drag Bug
  src/main/resources/static/js/multitool/DragDropManager.js
Labels: Front End

#1839 [Snyk] Security upgrade alpine from 3.20.2 to 3.20.3
  Dockerfile-ultra-lite
Labels: Docker

#1840 [Snyk] Security upgrade alpine from 3.20.2 to 3.20.3
  Dockerfile
Labels: Docker

#1848 Fixed reduce extra space between input field & button #1829
  src/main/resources/static/js/downloader.js
  src/main/resources/templates/fragments/common.html
Labels: Front End

#1800 Page Scale: add pageSize KEEP #1798
  src/main/java/stirling/software/SPDF/controller/api/ScalePagesController.java
  src/main/java/stirling/software/SPDF/model/api/PDFWithPageSize.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/scale-pages.html
Labels: Java, Front End, Translation, API

#1850 Minor fixes stopping invalid sessions
  src/main/java/stirling/software/SPDF/config/security/UserAuthenticationFilter.java
  src/main/java/stirling/software/SPDF/utils/RequestUriUtils.java
  src/test/java/stirling/software/SPDF/utils/RequestUriUtilsTest.java
Labels: Java, Back End, Security

#1854 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation

#1862 fix(stamp): radius styles of color input
  src/main/resources/static/css/theme/componentes.css
  src/main/resources/templates/misc/stamp.html
Labels: Front End

#1849 Changed <br> to get a consistent overlay-pdf form
  src/main/resources/templates/overlay-pdf.html
Labels: Front End

#1884 fix:Remove add image and Align download input file with same width as pdf file input
  src/main/resources/templates/misc/add-image.html
Labels: Front End

#1891 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation

#1893 Update add-watermark.html
  src/main/resources/templates/security/add-watermark.html
Labels: Front End

#1894 Metadata handling for all PDF endpoints
  src/main/java/stirling/software/SPDF/config/PdfMetadataService.java
  src/main/java/stirling/software/SPDF/controller/api/CropController.java
  src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  src/main/java/stirling/software/SPDF/controller/api/MultiPageLayoutController.java
  src/main/java/stirling/software/SPDF/controller/api/PdfImageRemovalController.java
  src/main/java/stirling/software/SPDF/controller/api/PdfOverlayController.java
  src/main/java/stirling/software/SPDF/controller/api/RearrangePagesPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/RotationController.java
  src/main/java/stirling/software/SPDF/controller/api/ScalePagesController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySectionsController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySizeController.java
  src/main/java/stirling/software/SPDF/controller/api/ToSinglePageController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertBookToPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertHtmlToPDF.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertImgPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertMarkdownToPdf.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertOfficeController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToBookController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToPDFA.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPDF.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ExtractCSVController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoSplitPdfController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/BlankPageController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/FlattenController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/OCRController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/OverlayImageController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/PageNumbersController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/RepairController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/java/stirling/software/SPDF/controller/api/security/PasswordController.java
  src/main/java/stirling/software/SPDF/controller/api/security/RedactController.java
  src/main/java/stirling/software/SPDF/controller/api/security/RemoveCertSignController.java
  src/main/java/stirling/software/SPDF/controller/api/security/SanitizeController.java
  src/main/java/stirling/software/SPDF/controller/api/security/WatermarkController.java
  src/main/java/stirling/software/SPDF/service/CustomPDDocumentFactory.java
  src/main/java/stirling/software/SPDF/utils/PdfUtils.java
  src/main/resources/messages_it_IT.properties
  src/test/java/stirling/software/SPDF/controller/api/RearrangePagesPDFControllerTest.java
  src/test/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPdfTest.java
Labels: Java, Translation, API

#1897 Fix: Left-align the submit button on each card for pdf operation
  src/main/resources/templates/misc/adjust-contrast.html
  src/main/resources/templates/pipeline.html
  src/main/resources/templates/security/add-password.html
  src/main/resources/templates/security/cert-sign.html
  src/main/resources/templates/security/change-permissions.html
  src/main/resources/templates/security/remove-cert-sign.html
  src/main/resources/templates/security/remove-password.html
  src/main/resources/templates/security/sanitize-pdf.html
Labels: Front End

#1902 Load pdf libs when needed
  src/main/resources/templates/convert/pdf-to-csv.html
  src/main/resources/templates/convert/pdf-to-pdfa.html
  src/main/resources/templates/crop.html
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/misc/add-image.html
  src/main/resources/templates/misc/adjust-contrast.html
  src/main/resources/templates/misc/change-metadata.html
  src/main/resources/templates/misc/compare.html
  src/main/resources/templates/misc/remove-annotations.html
  src/main/resources/templates/multi-tool.html
  src/main/resources/templates/rotate-pdf.html
  src/main/resources/templates/sign.html
Labels: Front End

#1907 Fix pdfa conversion
  scripts/replace_translation_line.sh
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToPDFA.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
Labels: Java, Translation, API

#1909 feat: rotate preview in multitool
  src/main/resources/static/js/multitool/ImageHighlighter.js
Labels: Front End

#1910 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation

#1925 fixed colorspace array exception
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImagesController.java
Labels: Java, API

#1927 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation

#1920 Updating pt-BR translation file.
  src/main/resources/messages_pt_BR.properties
Labels: Translation

#1912 Update messages_ja_JP.properties
  src/main/resources/messages_ja_JP.properties
Labels: Translation

#1915 length of card which was getting displayed on hovering is reduced
  src/main/resources/static/css/navbar.css
Labels: Front End

#1932 [FIX]: Reduce card size in "Get info on PDF" page
  src/main/resources/templates/security/get-info-on-pdf.html
Labels: Front End

#1933 [fix]: home button on view PDF page
  src/main/resources/static/pdfjs-legacy/images/toolbarButton-home.svg
Labels: Front End

#1940 Home page improvements
  src/main/resources/static/css/home.css
  src/main/resources/static/js/homecard.js
  src/main/resources/templates/fragments/featureGroupHeader.html
  src/main/resources/templates/home.html
Labels: Front End

#1943 Smaller italian optimizations
  src/main/resources/messages_it_IT.properties
Labels: Translation

#1885 Update LocalRunGuide.md
  LocalRunGuide.md
Labels: Documentation

#1934 [Bug fix] Favorite Icon highlighted with yellow color when selected
  src/main/resources/static/css/home.css
  src/main/resources/static/css/theme/theme.css
Labels: Front End

#1948 remove style color
  src/main/resources/templates/view-pdf.html
Labels: Front End

#1950 Fix startup errors on ultra-lite image
  Dockerfile-ultra-lite
Labels: Docker

#1913 Added functionality to use the next available port
  src/main/java/stirling/software/SPDF/SPdfApplication.java
  src/main/java/stirling/software/SPDF/controller/web/ConverterWebController.java
Labels: Java, Front End

#1947 [Bug fix] Tooltip support added for Theme & Settings in the Navigation bar
  src/main/resources/static/css/navbar.css
  src/main/resources/static/css/theme/font.css
  src/main/resources/templates/fragments/navbar.html
Labels: Front End

#1949 [fix]: check for encryption in PageNumbers
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
  src/main/java/stirling/software/SPDF/service/CustomPDDocumentFactory.java
Labels: Java, API

#1959 fix Show Javascript card layout
  src/main/java/stirling/software/SPDF/SPdfApplication.java
  src/main/resources/static/js/pipeline.js
  src/main/resources/templates/misc/show-javascript.html
Labels: Java, Front End

#1973 [Bug Fix] New Home Page Bug Fixes
  src/main/resources/static/css/home.css
  src/main/resources/static/js/homecard.js
Labels: Front End
