Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2024-12, with the labels that each got.

#2374 Fix submit button in crop by adding id
  src/main/resources/templates/crop.html
Labels: Bug, Front End, size:XS

#2369 Fix translations for watermark spacers
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:M

#2365 Fix: prevent fileInput.js from adding event listeners more than once
  src/main/resources/static/js/fileInput.js
Labels: Bug, Front End, size:S

#2370 added support for new line break in stampController
  src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java
Labels: Bug, Java, Back End, API, size:S

#2368 Fix drag and drop area for file choosers by adding separate ones
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/css/fileSelect.css
  src/main/resources/static/js/file-icon-factory.js
  src/main/resources/static/js/file-utils.js
  src/main/resources/static/js/fileInput.js
  src/main/resources/static/js/merge.js
  src/main/resources/static/js/uuid.js
  src/main/resources/templates/fragments/common.html
Labels: enhancement, Front End, Translation, size:XL

#2382 Fix deserialization failure in Change Metadata
  src/main/java/stirling/software/SPDF/controller/api/misc/MetadataController.java
  src/main/java/stirling/software/SPDF/utils/propertyeditor/StringToMapPropertyEditor.java
  src/main/resources/templates/misc/change-metadata.html
Labels: Bug, Java, Front End, Back End, API, size:M

#2389 Feature/undo page break
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/static/js/multitool/commands/add-page.js
  src/main/resources/static/js/multitool/commands/delete-page.js
  src/main/resources/static/js/multitool/commands/page-break.js
Labels: enhancement, Front End, size:XL

#2393 Fix missing upload button
  src/main/resources/static/css/fileSelect.css
Labels: Front End, size:XS

#2394 PDF Cert validation
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java
  src/main/java/stirling/software/SPDF/controller/api/security/ValidateSignatureController.java
  src/main/java/stirling/software/SPDF/controller/web/SecurityWebController.java
  src/main/java/stirling/software/SPDF/model/api/security/SignatureValidationRequest.java
  src/main/java/stirling/software/SPDF/model/api/security/SignatureValidationResult.java
  src/main/java/stirling/software/SPDF/service/CertificateValidationService.java
  src/main/resources/certdata.txt
  src/main/resources/messages_en_GB.properties
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/home.html
  src/main/resources/templates/security/validate-signature.html
Labels: enhancement, Java, Front End, Back End, Translation, Security, API, size:XL

#2397 Only download one file on sign cert
  src/main/resources/static/js/downloader.js
Labels: Front End, size:L

#2396 Feature: Show permissions as a separate tab
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
Labels: enhancement, Java, Back End, API, size:M

#2401 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:M

#2404 quick fixes
  src/main/java/stirling/software/SPDF/EE/LicenseKeyChecker.java
  src/main/resources/static/js/downloader.js
  src/main/resources/templates/releases.html
Labels: Bug, Java, Front End, size:S

#2405 Update German translation + remove unnecessary comment
  scripts/ignore_translation.toml
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
Labels: Documentation, Translation, size:L

#2408 english translation fixes
  src/main/resources/messages_en_GB.properties
Labels: Translation, size:M

#2410 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:XS

#2415 Text color selection for watermark
  src/main/java/stirling/software/SPDF/controller/api/security/WatermarkController.java
  src/main/java/stirling/software/SPDF/model/api/security/AddWatermarkRequest.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/security/add-watermark.html
Labels: enhancement, Java, Front End, Back End, Translation, API, size:M

#2416 feat: fa locale added
  README.md
  src/main/resources/messages_fa_IR.properties
  src/main/resources/static/images/flags/ir.svg
  src/main/resources/templates/fragments/languages.html
Labels: Documentation, enhancement, Front End, Translation, size:XXL

#2429 Update messages_pt_BR.properties
  src/main/resources/messages_pt_BR.properties
Labels: Translation, size:XL

#2412 Feature/1856/decrypt
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  src/main/java/stirling/software/SPDF/controller/api/security/PasswordController.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/js/DecryptFiles.js
  src/main/resources/static/js/download.js
  src/main/resources/static/js/downloader.js
  src/main/resources/static/js/draggable-utils.js
  src/main/resources/static/js/fileInput.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/static/js/pages/add-image.js
  src/main/resources/static/js/pages/adjust-contrast.js
  src/main/resources/static/js/pages/change-metadata.js
  src/main/resources/static/js/pages/crop.js
  src/main/resources/static/js/pages/pdf-to-csv.js
  src/main/resources/static/js/pages/sign.js
  src/main/resources/templates/convert/pdf-to-csv.html
  src/main/resources/templates/crop.html
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/fragments/errorBanner.html
  src/main/resources/templates/fragments/errorBannerPerPage.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/home.html
  src/main/resources/templates/misc/add-image.html
  src/main/resources/templates/misc/adjust-contrast.html
  src/main/resources/templates/misc/change-metadata.html
  src/main/resources/templates/misc/extract-images.html
  src/main/resources/templates/misc/replace-color.html
  src/main/resources/templates/multi-tool.html
  src/main/resources/templates/overlay-pdf.html
  src/main/resources/templates/pipeline.html
  src/main/resources/templates/sign.html
Labels: Documentation, enhancement, Java, Front End, Back End, Translation, API, Github, size:XXL

#2427 X-API-key to X-API-KEY and enable CSRF protection for all users
  README.md
  cucumber/features/steps/step_definitions.py
  exampleYmlFiles/test_cicd.yml
  src/main/java/stirling/software/SPDF/EE/LicenseKeyChecker.java
  src/main/java/stirling/software/SPDF/config/InitialSetup.java
  src/main/java/stirling/software/SPDF/config/security/InitialSecuritySetup.java
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/java/stirling/software/SPDF/config/security/UserAuthenticationFilter.java
  src/main/java/stirling/software/SPDF/config/security/UserBasedRateLimitingFilter.java
  src/main/java/stirling/software/SPDF/config/security/UserService.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySectionsController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertImgPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/OCRController.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessor.java
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  src/main/java/stirling/software/SPDF/controller/api/security/ValidateSignatureController.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/java/stirling/software/SPDF/model/api/security/SignatureValidationResult.java
  src/main/java/stirling/software/SPDF/service/CertificateValidationService.java
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
  src/main/resources/settings.yml.template
  test.sh
Labels: Documentation, Java, Back End, Docker, Security, API, Test, size:XL

#2436 [Snyk] Security upgrade alpine from 3.20.3 to 3.21.0
  Dockerfile-ultra-lite
Labels: Docker, size:XS

#2434 Security fix: Server-Side Request Forgery
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
Labels: Java, size:M

#2440 Fix collapsed menu issue on page reload
  src/main/resources/static/css/home.css
  src/main/resources/static/js/homecard.js
Labels: Bug, Front End, size:XS

#2443 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:S

#2444 Update messages_ja_JP.properties
  src/main/resources/messages_ja_JP.properties
Labels: Translation, size:L

#2442 add and refactor CN translate
  src/main/resources/messages_zh_CN.properties
Labels: Translation, size:XL

#2451 Full local webUI client
  .github/workflows/multiOSReleases.yml
  .github/workflows/releaseArtifacts.yml
  .gitignore
  Dockerfile
  Dockerfile-fat
  build.gradle
  src/main/java/stirling/software/SPDF/SPdfApplication.java
  src/main/java/stirling/software/SPDF/UI/WebBrowser.java
  src/main/java/stirling/software/SPDF/UI/impl/DesktopBrowser.java
  src/main/java/stirling/software/SPDF/UI/impl/LoadingWindow.java
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/config/security/InitialSecuritySetup.java
  src/main/resources/static/favicon.icns
Labels: Java, Front End, Back End, Docker, Security, Github, size:XL

#2441 CSRF token for decryption
  src/main/resources/static/js/DecryptFiles.js
Labels: enhancement, Front End, size:S

#2453 Csrf fixes
  build.gradle
  src/main/resources/static/js/downloader.js
  src/main/resources/static/js/fetch-utils.js
  src/main/resources/templates/account.html
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/misc/remove-annotations.html
  src/main/resources/templates/security/validate-signature.html
Labels: Front End, size:S

#2463 Add missing pdflib
  build.gradle
  src/main/resources/templates/merge-pdfs.html
Labels: Bug, Front End, size:XS

#2467 update python version used in pre commits
  .github/workflows/build.yml
Labels: Github, size:XS

#2468 Fix: Rename LANGS variable in init.sh to avoid clashing with LANGS env
  scripts/init.sh
Labels: Bug, Docker, size:XS

#2480 Remove Direct Logger and Use Lombok `@Slf4j`
  src/main/java/stirling/software/SPDF/LibreOfficeListener.java
  src/main/java/stirling/software/SPDF/SPdfApplication.java
  src/main/java/stirling/software/SPDF/config/AppConfig.java
  src/main/java/stirling/software/SPDF/config/ConfigInitializer.java
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/CustomOAuth2UserService.java
  src/main/java/stirling/software/SPDF/controller/api/CropController.java
  src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  src/main/java/stirling/software/SPDF/controller/api/MultiPageLayoutController.java
  src/main/java/stirling/software/SPDF/controller/api/RearrangePagesPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/RotationController.java
  src/main/java/stirling/software/SPDF/controller/api/ScalePagesController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySectionsController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySizeController.java
  src/main/java/stirling/software/SPDF/controller/api/ToSinglePageController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertImgPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToPDFA.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPDF.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ExtractCSVController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoRenameController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoSplitPdfController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/BlankPageController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImageScansController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImagesController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/FakeScanControllerWIP.java
  src/main/java/stirling/software/SPDF/controller/api/misc/FlattenController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/MetadataController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/OverlayImageController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/PageNumbersController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/RepairController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ShowJavascript.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/ApiDocService.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineController.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineDirectoryProcessor.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessor.java
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  src/main/java/stirling/software/SPDF/controller/api/security/PasswordController.java
  src/main/java/stirling/software/SPDF/controller/api/security/RedactController.java
  src/main/java/stirling/software/SPDF/controller/api/security/RemoveCertSignController.java
  src/main/java/stirling/software/SPDF/controller/web/GeneralWebController.java
  src/main/java/stirling/software/SPDF/controller/web/HomeWebController.java
  src/main/java/stirling/software/SPDF/model/api/PDFWithPageNums.java
  src/main/java/stirling/software/SPDF/service/CustomPDDocumentFactory.java
  src/main/java/stirling/software/SPDF/utils/FileMonitor.java
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
  src/main/java/stirling/software/SPDF/utils/ImageProcessingUtils.java
  src/main/java/stirling/software/SPDF/utils/PDFToFile.java
  src/main/java/stirling/software/SPDF/utils/PdfUtils.java
  src/main/java/stirling/software/SPDF/utils/ProcessExecutor.java
Labels: enhancement, Java, Front End, Back End, Security, API, size:L

#2481 Bump googleJavaFormat from 1.22.0 to 1.25.2
  .vscode/settings.json
  build.gradle
Labels: Java, Back End, size:XS

#2476 Fix img to pdf merge conversion type
  src/main/resources/static/js/downloader.js
  src/main/resources/templates/convert/img-to-pdf.html
Labels: Bug, Front End, size:S

#2483 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:S

#2485 Fix draggableElement is null by removing draggable.js
  src/main/resources/static/js/draggable.js
  src/main/resources/templates/sign.html
Labels: Front End, size:M

#2466 Fix drag and drop bugs and clean up UI
  src/main/resources/static/css/dragdrop.css
  src/main/resources/static/js/multitool/DragDropManager.js
  src/main/resources/static/js/multitool/commands/move-page.js
Labels: Bug, Front End, size:L

#2492 Fix: form data not being sent in multi
  src/main/resources/static/js/downloader.js
Labels: Bug, Front End, size:XS

#2497 Remove file input append
  src/main/resources/static/js/downloader.js
Labels: Bug, Front End, size:XS

#2499 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2500 Config mount check
  src/main/java/stirling/software/SPDF/config/AppConfig.java
  src/main/java/stirling/software/SPDF/service/PostHogService.java
Labels: Java, Back End, size:S

#2501 [Bugfix] A variety of tools miss PDFLib
  src/main/resources/templates/convert/pdf-to-csv.html
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/merge-pdfs.html
  src/main/resources/templates/misc/add-image.html
  src/main/resources/templates/misc/adjust-contrast.html
  src/main/resources/templates/misc/extract-images.html
  src/main/resources/templates/misc/remove-annotations.html
  src/main/resources/templates/misc/replace-color.html
  src/main/resources/templates/multi-tool.html
  src/main/resources/templates/overlay-pdf.html
  src/main/resources/templates/pipeline.html
  src/main/resources/templates/sign.html
Labels: Bug, Front End, size:S

#2503 Fix: Draw image with the original PDF page dimensions
  src/main/java/stirling/software/SPDF/utils/PdfUtils.java
Labels: Java, size:XS

#2505 Toolbar tweaks2
  src/main/resources/static/css/navbar.css
  src/main/resources/static/js/languageSelection.js
  src/main/resources/static/js/navbar.js
  src/main/resources/templates/fragments/navbar.html
Labels: Front End, size:L

#2507 remove redundant entries
  build.gradle
Labels: size:XS

#2509 standardize the submit button
  src/main/resources/templates/addUsers.html
  src/main/resources/templates/convert/pdf-to-csv.html
  src/main/resources/templates/crop.html
  src/main/resources/templates/login.html
  src/main/resources/templates/misc/change-metadata.html
  src/main/resources/templates/remove-image-pdf.html
  src/main/resources/templates/security/add-watermark.html
  src/main/resources/templates/security/auto-redact.html
  src/main/resources/templates/security/remove-watermark.html
Labels: Front End, size:S

#2513 Update and improve zh_TW Traditional Chinese locale
  src/main/resources/messages_zh_TW.properties
Labels: enhancement, Translation, size:L

#2525 Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: Bug, size:XS

#2528 Update check_properties.yml
  .github/workflows/check_properties.yml
Labels: Github, size:XS

#2530 Update check_properties.yml no. 2
  .github/workflows/check_properties.yml
Labels: Github, size:XS

#2529 Removing duplicate permissions
  .github/workflows/auto-labeler.yml
Labels: Github, size:XS

#2531 Update check_properties.yml no. 3
  .github/workflows/check_properties.yml
Labels: Github, size:XS

#2527 Update .pre-commit-config.yaml no. 2
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/PR-Demo-Comment.yml
  .github/workflows/PR-Demo-cleanup.yml
  .github/workflows/manage-label.yml
  .github/workflows/multiOSReleases.yml
  .github/workflows/releaseArtifacts.yml
  .pre-commit-config.yaml
Labels: Github, size:L

#2532 [Security] Dangerous-Workflow
  .github/workflows/check_properties.yml
Labels: Security, size:XS, Priority: Critical

#2533 [Security] Token permissions
  .github/workflows/build.yml
  .github/workflows/check_properties.yml
  .github/workflows/update-translations.yml
Labels: Security, Github, size:L, Priority: High

#2534 [Security] Token permissions no. 2
  .github/workflows/PR-Demo-cleanup.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/licenses-update.yml
  .github/workflows/manage-label.yml
  .github/workflows/multiOSReleases.yml
  .github/workflows/push-docker.yml
  .github/workflows/releaseArtifacts.yml
  .github/workflows/stale.yml
  .github/workflows/swagger.yml
  .github/workflows/sync_files.yml
Labels: Security, Github, size:M, Priority: High

#2538 Improve Markdown documentation a bit
  CONTRIBUTING.md
  DeveloperGuide.md
  HowToUseOCR.md
  LocalRunGuide.md
  README.md
  SECURITY.md
  Version-groups.md
Labels: Documentation, size:L

#2537 Update GitHub Actions: Upgrade create-pull-request and Enhance Workflow Configurations
  .github/workflows/licenses-update.yml
  .github/workflows/sync_files.yml
  .github/workflows/update-translations.yml
Labels: Security, Github, size:S, Priority: Medium

#2536 Docker labels
  Dockerfile
  Dockerfile-fat
  Dockerfile-ultra-lite
Labels: Docker, size:M

#2535 Update push-docker.yml with cosign
  .github/workflows/push-docker.yml
Labels: Github, size:M

#2540 Standardize Alpine base image format and version across all Dockerfiles
  Dockerfile
  Dockerfile-fat
  Dockerfile-ultra-lite
Labels: enhancement, Docker, size:XS

#2542 Rollback action-gh-release version from v2.2.0 to v2.1.0
  .github/workflows/multiOSReleases.yml
  .github/workflows/releaseArtifacts.yml
Labels: Bug, Github, size:XS

#2541 Docker rename for standardisation
  .github/workflows/push-docker.yml
  DeveloperGuide.md
  Dockerfile
  Dockerfile.fat
  Dockerfile.ultra-lite
  src/main/java/stirling/software/SPDF/config/security/CustomLogoutSuccessHandler.java
  src/main/java/stirling/software/SPDF/controller/web/AccountWebController.java
  test.sh
  test2.sh
Labels: Documentation, Java, Front End, Back End, Docker, Security, Github, size:M

#2543 Introduces pre-commit github-action
  .github/workflows/pre_commit.yml
Labels: enhancement, Github, size:M

#2546 Update pre_commit.yml
  .github/workflows/pre_commit.yml
Labels: Github, size:XS

#2547 add label Security to changed files
  .github/labeler-config.yml
Labels: Github, size:XS

#2548 used pre-commit/action
  .github/workflows/pre_commit.yml
Labels: size:S

#2551 rollback check_properties.yml
  .github/workflows/check_properties.yml
Labels: size:XS

#2550 Fix: duplicated mapping key
  .github/labeler-config.yml
Labels: size:XS

#2559 Update build.yml
  .github/workflows/build.yml
Labels: Github, size:S

#2563 Adding the missing translations in French
  src/main/resources/messages_fr_FR.properties
Labels: Translation, size:M

#2564 add permissions for `check_properties.yml`
  .github/workflows/check_properties.yml
Labels: Github, size:XS

#2567 removed `actions/checkout` for PR branch, use `gh`
  .github/workflows/check_properties.yml
Labels: Github, size:M

#2571 Move docs to website
  CONTRIBUTING.md
  Endpoint-groups.md
  FolderScanning.md
  LocalRunGuide.md
  PipelineFeature.md
  README.md
  Version-groups.md
  src/main/resources/templates/misc/ocr-pdf.html
  src/main/resources/templates/pipeline.html
Labels: size:XL

#2572 extends the .gitignore for cert and ssh
  .gitignore
Labels: size:XS

#2575 Fix file drag and drop
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/static/js/multitool/fileInput.js
  src/main/resources/templates/multi-tool.html
Labels: Bug, Front End, size:M
