Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2024-10, with the labels that each got.

#1980 Turkish translation
  src/main/resources/messages_tr_TR.properties
Labels: Translation

#1985 Searchbar Dynamically Resizes
  src/main/resources/static/css/navbar.css
Labels: Front End

#1982 commit for feature developing invert-replace color of a pdf for stirl…
  src/main/java/stirling/software/SPDF/Factories/ReplaceAndInvertColorFactory.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ReplaceAndInvertColorController.java
  src/main/java/stirling/software/SPDF/controller/web/OtherWebController.java
  src/main/java/stirling/software/SPDF/model/api/misc/HighContrastColorCombination.java
  src/main/java/stirling/software/SPDF/model/api/misc/ReplaceAndInvert.java
  src/main/java/stirling/software/SPDF/model/api/misc/ReplaceAndInvertColorRequest.java
  src/main/java/stirling/software/SPDF/service/misc/ReplaceAndInvertColorService.java
  src/main/java/stirling/software/SPDF/utils/misc/CustomColorReplaceStrategy.java
  src/main/java/stirling/software/SPDF/utils/misc/HighContrastColorReplaceDecider.java
  src/main/java/stirling/software/SPDF/utils/misc/InvertFullColorStrategy.java
  src/main/java/stirling/software/SPDF/utils/misc/PdfTextStripperCustom.java
  src/main/java/stirling/software/SPDF/utils/misc/ReplaceAndInvertColorStrategy.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/home.html
  src/main/resources/templates/misc/replace-color.html
Labels: Java, Front End, Translation, API

#1986 Added page counts to merge pdf tool
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/static/js/merge.js
  src/main/resources/templates/merge-pdfs.html
Labels: Front End, Translation, needs-changes

#1989 Update messages_zh_CN.properties
  src/main/resources/messages_zh_CN.properties
Labels: Translation

#1990 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation

#1957 Add tests via TestDriverAI
  .github/workflows/testdriver.yml
  testdriver/test.yml
Labels: Github

#2030 Update and improve zh_TW Traditional Chinese locale
  src/main/resources/messages_zh_TW.properties
Labels: Translation

#2029 Update messages_pt_BR.properties
  src/main/resources/messages_pt_BR.properties
Labels: Translation

#2022 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation

#2040 Major Enhancements to SAML2 and OAuth2 Integration with Simplified Security Configurations
  build.gradle
  src/main/java/stirling/software/SPDF/SPdfApplication.java
  src/main/java/stirling/software/SPDF/config/security/CustomLogoutSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/java/stirling/software/SPDF/config/security/UserAuthenticationFilter.java
  src/main/java/stirling/software/SPDF/config/security/UserService.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/CustomOAuth2LogoutSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml/ConvertResponseToAuthentication.java
  src/main/java/stirling/software/SPDF/config/security/saml/CustomSAMLAuthenticationFailureHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml/CustomSAMLAuthenticationSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml/SAMLLogoutSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml/Saml2AuthorityAttributeLookup.java
  src/main/java/stirling/software/SPDF/config/security/saml/Saml2AuthorityAttributeLookupImpl.java
  src/main/java/stirling/software/SPDF/config/security/saml/SamlAssertionUtils.java
  src/main/java/stirling/software/SPDF/config/security/saml/SamlConfig.java
  src/main/java/stirling/software/SPDF/config/security/saml/ScimSaml2AuthenticatedPrincipal.java
  src/main/java/stirling/software/SPDF/config/security/saml/SimpleScimMappings.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CertificateUtils.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2AuthenticatedPrincipal.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2AuthenticationFailureHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2AuthenticationSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2ResponseAuthenticationConverter.java
  src/main/java/stirling/software/SPDF/config/security/session/SessionPersistentRegistry.java
  src/main/java/stirling/software/SPDF/controller/api/UserController.java
  src/main/java/stirling/software/SPDF/controller/web/AccountWebController.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/java/stirling/software/SPDF/model/Provider.java
  src/main/resources/settings.yml.template
  src/main/resources/templates/addUsers.html
  src/main/resources/templates/login.html
Labels: Java, Front End, Back End, Security, API

#2045 Update messages_bg_BG.properties
  src/main/resources/messages_bg_BG.properties
Labels: Translation

#2046 Update and improve zh_TW Traditional Chinese locale
  src/main/resources/messages_zh_TW.properties
Labels: Translation

#2042 Update messages_pl_PL.properties
  src/main/resources/messages_pl_PL.properties
Labels: Translation

#1996 Fixed layering issue with z-index, and added smoother transitions for…
  package-lock.json
  src/main/resources/static/css/sign.css
  src/main/resources/static/js/draggable.js
  src/main/resources/templates/sign.html
Labels: Front End

#2058 Default terms and conditions to stirlingpdf.com
  src/main/java/stirling/software/SPDF/config/InitialSetup.java
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/java/stirling/software/SPDF/config/security/UserService.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/UserServiceInterface.java
  src/main/java/stirling/software/SPDF/service/PostHogService.java
  src/main/resources/settings.yml.template
Labels: Java, Back End, Security, API

#2061 French translation improvements
  src/main/resources/messages_fr_FR.properties
Labels: Translation

#2065 Removed horizontal scroll logic from multi-tool template
  src/main/resources/static/js/multitool/horizontalScroll.js
  src/main/resources/templates/multi-tool.html
Labels: Front End

#2070 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation

#2077 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation

#2084 visual certificate signing
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/resources/static/images/signature.png
  src/main/resources/templates/security/cert-sign.html
Labels: Java, Front End, API

#2085 added some missing translations
  src/main/resources/messages_sv_SE.properties
Labels: Translation

#2082 Auto detect presence of external dependencies (LibreOffice etc) and disable/enable features dynamically
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/config/ExternalAppDepConfig.java
Labels: Java

#2102 Spanish translate
  src/main/resources/messages_es_ES.properties
Labels: enhancement, Translation, size:L

#2105 Optimierung der SAML2-Integration und Verbesserung der Zertifikats- und Fehlerbehandlung
  src/main/java/stirling/software/SPDF/config/security/saml2/CertificateUtils.java
  src/main/java/stirling/software/SPDF/controller/web/AccountWebController.java
  src/main/resources/templates/addUsers.html
Labels: enhancement, Java, Front End, Back End, Security, size:M

#2124 Feature/298 improve compare performance
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/js/compare/diff.js
  src/main/resources/static/js/compare/pdfWorker.js
  src/main/resources/templates/misc/compare.html
Labels: enhancement, Front End, Translation, size:XXL

#2126 Fix csrf
  build.gradle
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/resources/templates/change-creds.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/merge-pdfs.html
  src/main/resources/templates/misc/adjust-contrast.html
  src/main/resources/templates/misc/remove-annotations.html
  src/main/resources/templates/remove-image-pdf.html
  src/main/resources/templates/security/add-password.html
  src/main/resources/templates/security/add-watermark.html
  src/main/resources/templates/security/auto-redact.html
  src/main/resources/templates/security/cert-sign.html
  src/main/resources/templates/security/change-permissions.html
  src/main/resources/templates/security/remove-cert-sign.html
  src/main/resources/templates/security/remove-password.html
  src/main/resources/templates/security/remove-watermark.html
  src/main/resources/templates/security/sanitize-pdf.html
Labels: Java, Front End, Back End, Security, size:M

#2108 Update id_ID Translation and fix some grammars
  src/main/resources/messages_id_ID.properties
Labels: Translation, size:XL

#2109 chore(helm): bump chart version according to semver
  .github/scripts/gradle_to_chart.py
Labels: enhancement, Github, size:M

#2135 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:S

#2138 [bug fix] Update compress-pdf.html
  src/main/resources/templates/misc/compress-pdf.html
Labels: Bug, Front End, size:XS

#2140 navbar.css: prevent overlapping of elements
  src/main/resources/static/css/navbar.css
Labels: Bug, Front End, size:XS

#2143 fix signature logo not loading and add option to disable it
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/java/stirling/software/SPDF/model/api/security/SignPDFWithCertRequest.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/templates/security/cert-sign.html
Labels: Bug, Java, Front End, Translation, API, size:M
