Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2024-11, with the labels that each got.

#2146 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2152 fixed minor bugs in Markdown
  DATABASE.md
  DeveloperGuide.md
  FolderScanning.md
  HowToAddNewLanguage.md
  HowToUseOCR.md
  LocalRunGuide.md
  PipelineFeature.md
  README.md
  Version-groups.md
  src/main/resources/settings.yml.template
Labels: Documentation, Back End, size:XL

#2153 re-config labeler & add new labels
  .github/labeler-config.yml
  .github/labels.yml
Labels: Github, size:M

#2158 Fix: redeclaration of const and add: tranlation placeholder for Session Expiry Messages
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/static/js/downloader.js
  src/main/resources/templates/fragments/common.html
Labels: Front End, Translation, size:M

#2159 Fix: Path correction to draggable.js #2154 + little makeup
  src/main/resources/templates/sign.html
Labels: Front End, size:XL

#2156 Fix: Add missing .map file for minified files
  src/main/resources/static/css/bootstrap.min.css.map
  src/main/resources/static/js/thirdParty/bootstrap.min.js.map
  src/main/resources/static/js/thirdParty/interact.min.js.map
  src/main/resources/static/js/thirdParty/pdf-lib.min.js.map
  src/main/resources/static/js/thirdParty/popper.min.js.map
  src/main/resources/static/js/thirdParty/signature_pad.umd.min.js.map
Labels: Front End, size:XS

#2161 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2164 Completed translations for 19 languages using AI
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
Labels: Translation, size:XXL

#2166 Corrects AI generated translation
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:S, Priority: Medium

#2162 Fix: Navbar layout overflow
  src/main/resources/templates/fragments/navbar.html
Labels: Bug, Front End, size:XS, Priority: Medium

#2184 fix remmeber me
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/java/stirling/software/SPDF/repository/JPATokenRepositoryImpl.java
  src/main/java/stirling/software/SPDF/repository/PersistentLoginRepository.java
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/templates/login.html
Labels: Bug, Java, Front End, Back End, Translation, Security, size:M

#2188 Update and improve zh_TW Traditional Chinese locale
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:S

#2193 [Feature] Set Executor Instances limits dynamically from properties
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/java/stirling/software/SPDF/utils/ProcessExecutor.java
  src/main/resources/application.properties
  src/main/resources/settings.yml.template
Labels: enhancement, Java, Back End, size:L

#2197 Searchbar in nav auto select, and exe nolonger disable CLI
  build.gradle
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/config/ExternalAppDepConfig.java
  src/main/resources/static/js/search.js
Labels: Java, Front End, Back End, size:M

#2201 Add option to insert blank page between pages in Multi-tool (#2194)
  src/main/resources/static/css/pdfActions.css
  src/main/resources/static/js/multitool/PdfActionsManager.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/templates/multi-tool.html
Labels: enhancement, Front End, size:L

#2203 Fix: Card has no favorite icon
  src/main/resources/static/js/homecard.js
Labels: Bug, Front End, size:S

#2208 feat: move helm chart to https://github.com/Stirling-Tools/Stirling-PDF-chart
  .github/scripts/gradle_to_chart.py
  .github/workflows/lint-helm-charts.yml-disabled
  .github/workflows/release-helm-charts.yml-disabled
  .github/workflows/sync_files.yml
  .pre-commit-config.yaml
  README.md
  chart/stirling-pdf/Chart.yaml
  chart/stirling-pdf/README.md
  chart/stirling-pdf/README.md.gotmpl
  chart/stirling-pdf/templates/NOTES.txt
  chart/stirling-pdf/templates/_helpers.tpl
  chart/stirling-pdf/templates/deployment.yaml
  chart/stirling-pdf/templates/ingress.yaml
  chart/stirling-pdf/templates/pv.yaml
  chart/stirling-pdf/templates/pvc.yaml
  chart/stirling-pdf/templates/service.yaml
  chart/stirling-pdf/templates/serviceaccount.yaml
  chart/stirling-pdf/templates/servicemonitor.yaml
  chart/stirling-pdf/values.yaml
  cr.yaml
Labels: Documentation, Github, size:XXL

#2211 Fix: Reading the username based on the login method.
  src/main/java/stirling/software/SPDF/config/security/UserService.java
Labels: Bug, Java, Back End, Security, size:S

#2210 Update messages_ca_CA.properties
  src/main/resources/messages_ca_CA.properties
Labels: Translation, size:M

#2219 Restricting file input to .md files for Markdown to PDF conversion
  src/main/resources/templates/convert/markdown-to-pdf.html
Labels: enhancement, Front End, size:XS

#2223 Removes references to nonexistent endpoint
  Endpoint-groups.md
  Version-groups.md
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
Labels: Documentation, Java, Back End, size:XS

#2222 Catalan Translation - Stirling PDF String Updates
  README.md
  scripts/ignore_translation.toml
  src/main/resources/messages_ca_CA.properties
Labels: Documentation, Translation, size:XXL

#2224 adds missing dependencies in the endpoints
  Endpoint-groups.md
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
Labels: Documentation, Java, Back End, size:L

#2226 Mention HTTP error 413 in FAQ
  README.md
Labels: Documentation, size:XS

#2221 Fix canvas crop
  src/main/resources/templates/crop.html
Labels: Bug, Front End, size:M

#2220 Increase watermark coverage to fill page (#2049)
  src/main/java/stirling/software/SPDF/controller/api/security/WatermarkController.java
Labels: Bug, Java, Back End, API, size:S

#2232 Setup new docker org stirlingtools/stirling-pdf
  .github/workflows/push-docker.yml
Labels: size:XS

#2200 Feature/1976/multi tool multiple pages
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/static/css/multi-tool.css
  src/main/resources/static/css/pdfActions.css
  src/main/resources/static/css/theme/font.css
  src/main/resources/static/js/multitool/PdfActionsManager.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/templates/multi-tool.html
Labels: enhancement, Front End, Translation, size:L

#2234 Fix: Ensure backend receives false when checkbox is unchecked in split-pdf-by-chapters feature
  src/main/resources/templates/split-pdf-by-chapters.html
Labels: Bug, Front End, size:XS

#2238 Add: missing swagger Tag
  src/main/java/stirling/software/SPDF/controller/api/misc/ReplaceAndInvertColorController.java
  src/main/java/stirling/software/SPDF/controller/api/security/WatermarkController.java
  src/main/java/stirling/software/SPDF/controller/web/SignatureController.java
Labels: Java, Front End, Back End, API, size:XS

#2237 added title display on hovering, added missing german translations
  scripts/ignore_translation.toml
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/fragments/navbar.html
Labels: Documentation, Front End, Translation, size:M

#2240 Prohibit the registration of unauthorized usernames
  src/main/java/stirling/software/SPDF/config/security/UserService.java
Labels: Java, Back End, Security, size:XS

#2239 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:S

#2247 Multitool advertising
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/extract-page.html
  src/main/resources/templates/fragments/multi-toolAdvert.html
  src/main/resources/templates/merge-pdfs.html
  src/main/resources/templates/pdf-organizer.html
  src/main/resources/templates/remove-pages.html
  src/main/resources/templates/rotate-pdf.html
  src/main/resources/templates/split-pdfs.html
Labels: Front End, Translation, size:L

#2248 Clear file inputs after jobs
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/js/downloader.js
  src/main/resources/static/js/merge.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/templates/merge-pdfs.html
  src/main/resources/templates/multi-tool.html
  src/main/resources/templates/rotate-pdf.html
Labels: enhancement, Front End, Translation, size:M

#2250 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2256 Fixing bug: Add Image makes random changes to image (#2246)
  src/main/resources/static/js/draggable-utils.js
Labels: Bug, Front End, size:L

#2228 Fix canvas pdf to csv
  src/main/resources/templates/convert/pdf-to-csv.html
Labels: Bug, Front End, size:M

#2260 Create PR-Demos.yml
  .github/workflows/PR-Demos.yml
  build.gradle
Labels: Github, size:L

#2262 shows the titles of the buttons
  src/main/resources/static/css/navbar.css
  src/main/resources/templates/fragments/navbar.html
Labels: Front End, size:S

#2261 Create PR-Demo-Comment.yml
  .github/workflows/PR-Demo-Comment.yml
Labels: Github, size:L

#2263 Read login data from application.properties
  src/main/java/stirling/software/SPDF/config/security/database/DatabaseBackupHelper.java
Labels: Java, Back End, Security, size:S

#2271 Fix id typo for "cropPdfCanvas" querySelector
  src/main/resources/static/js/downloader.js
Labels: Bug, Front End, size:XS, Priority: High

#2272 Update MetricsAggregatorService.java
  src/main/java/stirling/software/SPDF/service/MetricsAggregatorService.java
Labels: size:S

#2275 Frooodle patch 8
  .github/workflows/check_properties.yml
Labels: Github, size:M

#2273 Metrics changes
  src/main/resources/static/js/downloader.js
  src/main/resources/templates/fragments/common.html
Labels: Front End, size:M

#2276 Update German language
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:XS

#2282 Update Arabic language
  src/main/resources/messages_ar_AR.properties
Labels: Translation, size:M

#2290 Hover tools tooltips
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/static/css/multi-tool.css
  src/main/resources/static/css/pdfActions.css
  src/main/resources/static/js/multitool/PdfActionsManager.js
  src/main/resources/templates/multi-tool.html
Labels: enhancement, Front End, Translation, size:M

#2291 try to reduce the permission; update only translation files
  .github/workflows/check_properties.yml
Labels: Github, size:M

#2293 Fix: Convert a single string in the array to a list array
  .github/scripts/check_language_properties.py
Labels: Github, size:XS

#2289 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:S

#2235 Bored waiting button doesnt remove itself after processing (#2079)
  src/main/resources/static/js/downloader.js
Labels: Bug, Front End, size:S

#2294 Feature/2198/multitool multi select move pages
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/static/css/dragdrop.css
  src/main/resources/static/css/pdfActions.css
  src/main/resources/static/js/multitool/DragDropManager.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/templates/multi-tool.html
Labels: enhancement, Java, Front End, Back End, Translation, API, size:M

#2302 Fix file clear for errors
  src/main/resources/static/js/downloader.js
Labels: Bug, Front End, size:S

#2301 Posthog multitool
  src/main/resources/static/js/multitool/PdfContainer.js
Labels: enhancement, Front End, size:M

#2278 Sign multiple PDF pages at the same time in the same location (#2008)
  src/main/resources/static/css/sign.css
  src/main/resources/static/js/draggable-utils.js
  src/main/resources/templates/sign.html
Labels: enhancement, Front End, size:XL

#2309 Fix: Fixes dependency bug and replaces obsolete method
  build.gradle
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
Labels: Java, Back End, Security, size:XS

#2307 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2306 Fix: Prevents duplicate listing of search results
  src/main/resources/static/js/search.js
Labels: Bug, Front End, size:XS

#2303 Improves security when processing properties files
  .github/scripts/check_language_properties.py
  .github/workflows/check_properties.yml
Labels: Github, size:L

#2315 French translation (again)
  src/main/resources/messages_fr_FR.properties
Labels: Translation, size:M

#2313 improves readability
  .github/scripts/check_language_properties.py
Labels: Github, size:M

#2312 Extract tables from PDF to CSV using Tabula
  build.gradle
  src/main/java/stirling/software/SPDF/controller/api/converters/ExtractCSVController.java
  src/main/java/stirling/software/SPDF/controller/api/strippers/PDFTableStripper.java
  src/main/java/stirling/software/SPDF/pdf/FlexibleCSVWriter.java
Labels: enhancement, Java, Back End, API, size:L

#2320 Fix: id for submit button added
  src/main/resources/templates/convert/pdf-to-csv.html
Labels: Bug, Front End, size:XS

#2314 Bump com.h2database:h2 from 2.1.214 to 2.3.232
  build.gradle
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/java/stirling/software/SPDF/controller/web/DatabaseWebController.java
  src/main/resources/application.properties
  src/main/resources/templates/database.html
Labels: Java, Front End, Back End, Security, size:S

#2325 Add tooltip to sign add to all pages feature
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/css/general.css
  src/main/resources/static/css/multi-tool.css
  src/main/resources/templates/sign.html
Labels: enhancement, Front End, Translation, size:M

#2328 Additional sign tooltips
  src/main/resources/messages_en_GB.properties
  src/main/resources/templates/sign.html
Labels: enhancement, Front End, Translation, size:S

#2334 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:S

#2335 Fix: input file overwrite in merge
  src/main/resources/static/js/fileInput.js
  src/main/resources/static/js/merge.js
Labels: Front End, size:S

#2347 Azerbaijani Language Translation
  src/main/resources/messages_az_AZ.properties
Labels: enhancement, Translation, size:L

#2350 Fix: page break insertion functionality in Multi Tool
  src/main/resources/static/js/multitool/PdfContainer.js
Labels: Bug, Front End, size:M

#2348 Feature: Undo Redo options multi tool #2297
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/static/js/multitool/PdfActionsManager.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/static/js/multitool/UndoManager.js
  src/main/resources/static/js/multitool/commands/command.js
  src/main/resources/static/js/multitool/commands/delete-page.js
  src/main/resources/static/js/multitool/commands/move-page.js
  src/main/resources/static/js/multitool/commands/remove.js
  src/main/resources/static/js/multitool/commands/rotate.js
  src/main/resources/static/js/multitool/commands/select.js
  src/main/resources/static/js/multitool/commands/split.js
  src/main/resources/templates/multi-tool.html
Labels: enhancement, Front End, Translation, size:M

#2357 Fix Array.from syntax in nonmultiple file upload
  src/main/resources/static/js/fileInput.js
Labels: Bug, Front End, size:XS

#2360 fixes and other changes and debug of WIP SAML
  build.gradle
  cucumber/features/external.feature
  src/main/java/stirling/software/SPDF/EE/EEAppConfig.java
  src/main/java/stirling/software/SPDF/EE/LicenseKeyChecker.java
  src/main/java/stirling/software/SPDF/config/ExternalAppDepConfig.java
  src/main/java/stirling/software/SPDF/config/security/InitialSecuritySetup.java
  src/main/java/stirling/software/SPDF/config/security/SecurityConfiguration.java
  src/main/java/stirling/software/SPDF/config/security/UserService.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CertificateUtils.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2AuthenticationSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2ResponseAuthenticationConverter.java
  src/main/java/stirling/software/SPDF/controller/api/UserController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/OCRController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/RepairController.java
  src/main/java/stirling/software/SPDF/model/AuthenticationType.java
  src/main/java/stirling/software/SPDF/repository/UserRepository.java
  src/main/java/stirling/software/SPDF/service/PdfMetadataService.java
  src/main/java/stirling/software/SPDF/utils/FileToPdf.java
  src/main/resources/application.properties
  src/main/resources/settings.yml.template
  src/main/resources/static/js/fileInput.js
  src/main/resources/templates/addUsers.html
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/misc/compare.html
  test.sh
Labels: Java, Front End, Back End, Security, API, Test, size:XL

#2359 Fix allowing multiple files to be dropped onto a single file input
  src/main/resources/static/js/fileInput.js
Labels: Bug, Front End, size:XS
