Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-09, with the labels that each got.

#4280 refactor(ssrf): default enum MEDIUM prevents OFF=false
  .gitignore
  app/common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  app/common/src/main/java/stirling/software/common/service/SsrfProtectionService.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPDF.java
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/templates/convert/url-to-pdf.html
  app/core/src/test/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPdfTest.java
Labels: Java, Front End, Back End, Translation, API, Test, size:L, refactor

#4341 Add linting to frontend
  .editorconfig
  .github/workflows/build.yml
  .vscode/extensions.json
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/services/pdfExportService.ts
Labels: Docker, v2, Github, size:M, Devtools

#4321 feat: Add Lombok @Getter and @Setter annotations to reduce boilerplate code in multiple classes
  app/common/src/main/java/stirling/software/common/util/ProcessExecutor.java
  app/common/src/main/java/stirling/software/common/util/TempFile.java
  app/common/src/main/java/stirling/software/common/util/TempFileRegistry.java
  app/core/src/main/java/org/apache/pdfbox/examples/signature/CreateSignatureBase.java
  app/core/src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/EditTableOfContentsController.java
  app/core/src/main/java/stirling/software/SPDF/controller/web/GeneralWebController.java
  app/core/src/main/java/stirling/software/SPDF/controller/web/MetricsController.java
  app/core/src/main/java/stirling/software/SPDF/model/ApiEndpoint.java
  app/core/src/main/java/stirling/software/SPDF/model/api/misc/ScannerEffectRequest.java
  app/core/src/main/java/stirling/software/SPDF/pdf/TextFinder.java
  app/proprietary/src/main/java/stirling/software/proprietary/audit/AuditEventType.java
  app/proprietary/src/main/java/stirling/software/proprietary/audit/AuditLevel.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/AttemptCounter.java
Labels: enhancement, Java, Front End, Back End, Security, API, size:L

#4316 feat(convert): PDF conversion with unoconvert fallback soffice
  app/core/src/main/java/stirling/software/SPDF/controller/api/converters/ConvertOfficeController.java
Labels: enhancement, Java, Back End, API, size:L, pr-deployed

#4251 feat(database): make backup schedule configurable via system keys
  DATABASE.md
  app/common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  app/core/src/main/resources/settings.yml.template
  app/proprietary/src/main/java/stirling/software/proprietary/security/database/ScheduledTasks.java
Labels: Documentation, enhancement, Java, Back End, Security, size:S, pr-deployed

#4140 test(common): add dedicated unit tests for FileInfo and InputStreamTemplateResource
  app/common/src/main/java/stirling/software/common/model/InputStreamTemplateResource.java
  app/common/src/test/java/stirling/software/common/model/FileInfoTest.java
  app/common/src/test/java/stirling/software/common/model/InputStreamTemplateResourceTest.java
  app/common/src/test/java/stirling/software/common/util/FileInfoTest.java
Labels: Java, Test, size:L

#4219 Replace uses of `Arrays.asList()` with either List.of() or Collections.singletonList()
  app/core/src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessor.java
  app/core/src/main/java/stirling/software/SPDF/service/ApiDocService.java
  app/core/src/main/java/stirling/software/SPDF/service/CertificateValidationService.java
  app/core/src/test/java/stirling/software/SPDF/controller/api/MergeControllerTest.java
  app/core/src/test/java/stirling/software/SPDF/service/PdfImageRemovalServiceTest.java
Labels: Java, Back End, API, Test, size:M

#4261 feat(common): add `ChecksumUtils` for MD5/SHA*/CRC32/Adler32 with Base64 and multi-algorithm support
  app/common/src/main/java/stirling/software/common/util/ChecksumUtils.java
  app/common/src/test/java/stirling/software/common/util/ChecksumUtilsTest.java
Labels: enhancement, Java, Test, size:L

#4344 Enable ESLint no-useless-escape rule
  frontend/eslint.config.mjs
  frontend/scripts/generate-licenses.js
Labels: v2, size:XS

#4384 Update messages_tr_TR.properties
  app/core/src/main/resources/messages_tr_TR.properties
Labels: Translation, size:XS

#4343 Enable ESLint no-empty-pattern rule
  frontend/eslint.config.mjs
  frontend/src/components/shared/QuickAccessBar.tsx
Labels: v2, size:XS

#4348 Enable ESLint no-case-declarations rule
  frontend/eslint.config.mjs
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/services/enhancedPDFProcessingService.ts
  frontend/src/services/fileAnalyzer.ts
Labels: v2, size:M

#4390 fix(security): prevent NPE on logout when JWT service is unavailable
  app/proprietary/src/main/java/stirling/software/proprietary/security/CustomLogoutSuccessHandler.java
Labels: Java, Security, size:S, Bugfix

#4350 Enable ESLint ban-ts-comment rule
  frontend/eslint.config.mjs
  frontend/src/hooks/tools/convert/useConvertParametersAutoDetection.test.ts
Labels: v2, size:XS

#4393 fix: add missing MediaType import in SplitPdfBySectionsController
  app/core/src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySectionsController.java
Labels: Java, Back End, API, size:XS, Bugfix

#4395 Bump version from 1.3.0 to 1.3.1
  build.gradle
Labels: size:XS, Gradle

#4244 V2 Auto rename
  .vscode/settings.json
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/tools/autoRename/AutoRenameSettings.tsx
  frontend/src/components/tools/automate/ToolSelector.tsx
  frontend/src/components/tools/shared/ToolWorkflowTitle.tsx
  frontend/src/components/tools/shared/renderToolButtons.tsx
  frontend/src/components/tools/toolPicker/ToolButton.tsx
  frontend/src/components/tooltips/useAutoRenameTips.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/autoRename/useAutoRenameOperation.ts
  frontend/src/hooks/tools/autoRename/useAutoRenameParameters.ts
  frontend/src/hooks/tools/shared/useToolApiCalls.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/tools/AutoRename.tsx
  frontend/src/types/fileContext.ts
  frontend/src/utils/automationExecutor.ts
  frontend/src/utils/toolResponseProcessor.ts
Labels: v2, size:L, Devtools

#4402 login_fix
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/CustomUserDetailsService.java
  build.gradle
Labels: Java, Security, size:M, Gradle, pr-deployed

#4404 fix: try-with-resources for Streams interacting with Files to ensure proper resource management
  app/common/src/main/java/stirling/software/common/util/FileToPdf.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/converters/ConvertImgPDFController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/filters/FilterController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImageScansController.java
  app/core/src/main/java/stirling/software/SPDF/service/SignatureService.java
Labels: Java, Back End, API, size:M, Bugfix

#4165 Update hungarian translation for editTableOfContents strings
  app/core/src/main/resources/messages_hu_HU.properties
Labels: Translation, size:S

#4415 Fix types of onParameterChange methods
  frontend/src/components/tools/addPassword/AddPasswordSettings.tsx
  frontend/src/components/tools/changePermissions/ChangePermissionsSettings.tsx
  frontend/src/components/tools/compress/CompressSettings.tsx
  frontend/src/components/tools/convert/ConvertFromEmailSettings.tsx
  frontend/src/components/tools/convert/ConvertFromImageSettings.tsx
  frontend/src/components/tools/convert/ConvertFromWebSettings.tsx
  frontend/src/components/tools/convert/ConvertSettings.tsx
  frontend/src/components/tools/convert/ConvertToImageSettings.tsx
  frontend/src/components/tools/convert/ConvertToPdfaSettings.tsx
  frontend/src/components/tools/ocr/AdvancedOCRSettings.tsx
  frontend/src/components/tools/ocr/OCRSettings.tsx
  frontend/src/components/tools/removePassword/RemovePasswordSettings.tsx
  frontend/src/components/tools/sanitize/SanitizeSettings.tsx
  frontend/src/components/tools/split/SplitSettings.tsx
Labels: v2, size:L, Bugfix

#4359 Set i18n to load only current language
  frontend/src/i18n.ts
Labels: v2, size:XS

#4235 Add Merge UI to V2
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/tools/merge/MergeFileSorter.test.tsx
  frontend/src/components/tools/merge/MergeFileSorter.tsx
  frontend/src/components/tools/merge/MergeSettings.test.tsx
  frontend/src/components/tools/merge/MergeSettings.tsx
  frontend/src/components/tools/shared/FileStatusIndicator.tsx
  frontend/src/components/tools/shared/FilesToolStep.tsx
  frontend/src/components/tools/shared/createToolFlow.tsx
  frontend/src/components/tooltips/useMergeTips.tsx
  frontend/src/contexts/file/FileReducer.ts
  frontend/src/contexts/file/fileHooks.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/merge/useMergeOperation.test.ts
  frontend/src/hooks/tools/merge/useMergeOperation.ts
  frontend/src/hooks/tools/merge/useMergeParameters.test.ts
  frontend/src/hooks/tools/merge/useMergeParameters.ts
  frontend/src/hooks/tools/shared/useBaseTool.ts
  frontend/src/tools/Automate.tsx
  frontend/src/tools/Convert.tsx
  frontend/src/tools/Flatten.tsx
  frontend/src/tools/Merge.tsx
  frontend/src/tools/RemoveCertificateSign.tsx
  frontend/src/tools/Repair.tsx
  frontend/src/tools/Sanitize.tsx
  frontend/src/tools/SingleLargePage.tsx
  frontend/src/tools/UnlockPdfForms.tsx
  testing/test_pdf_1.pdf
  testing/test_pdf_2.pdf
  testing/test_pdf_3.pdf
  testing/test_pdf_4.pdf
Labels: v2, size:XL

#4430 Change tips icon to i circle
  frontend/src/components/tools/shared/ToolStep.tsx
  frontend/src/components/tools/shared/ToolWorkflowTitle.tsx
Labels: v2, size:XS

#4446 V2 Tool - Auto split
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/shared/CardSelector.tsx
  frontend/src/components/tools/split/SplitSettings.tsx
  frontend/src/components/tooltips/useSplitMethodTips.ts
  frontend/src/components/tooltips/useSplitSettingsTips.ts
  frontend/src/components/tooltips/useSplitTips.ts
  frontend/src/constants/splitConstants.ts
  frontend/src/hooks/tools/split/useSplitOperation.ts
  frontend/src/hooks/tools/split/useSplitParameters.ts
  frontend/src/tools/Split.tsx
Labels: v2, size:XL

#4452 V2 rotate
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/tools/rotate/RotateSettings.tsx
  frontend/src/components/tooltips/useRotateTips.ts
  frontend/src/contexts/file/fileHooks.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/rotate/useRotateOperation.test.ts
  frontend/src/hooks/tools/rotate/useRotateOperation.ts
  frontend/src/hooks/tools/rotate/useRotateParameters.test.ts
  frontend/src/hooks/tools/rotate/useRotateParameters.ts
  frontend/src/hooks/tools/shared/useBaseTool.ts
  frontend/src/tools/Merge.tsx
  frontend/src/tools/Rotate.tsx
  frontend/src/utils/urlMapping.ts
Labels: v2, size:XL

#4394 change bulk selection panel to allow more versatile input
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/pageEditor/BulkSelectionPanel.tsx
  frontend/src/components/pageEditor/PageEditor.tsx
  frontend/src/components/pageEditor/bulkSelectionPanel/AdvancedSelectionPanel.tsx
  frontend/src/components/pageEditor/bulkSelectionPanel/BulkSelection.ts
  frontend/src/components/pageEditor/bulkSelectionPanel/BulkSelectionPanel.module.css
  frontend/src/components/pageEditor/bulkSelectionPanel/OperatorsSection.tsx
  frontend/src/components/pageEditor/bulkSelectionPanel/PageSelectionInput.tsx
  frontend/src/components/pageEditor/bulkSelectionPanel/SelectPages.tsx
  frontend/src/components/pageEditor/bulkSelectionPanel/SelectedPagesDisplay.tsx
  frontend/src/components/pageEditor/commands/pageCommands.ts
  frontend/src/components/shared/RightRail.tsx
  frontend/src/components/shared/Tooltip.tsx
  frontend/src/components/shared/TopControls.tsx
  frontend/src/components/shared/tooltip/Tooltip.README.md
  frontend/src/components/tools/shared/ToolStep.tsx
  frontend/src/components/tooltips/usePageSelectionTips.ts
  frontend/src/styles/theme.css
  frontend/src/utils/bulkselection/README.md
  frontend/src/utils/bulkselection/parseSelection.test.ts
  frontend/src/utils/bulkselection/parseSelection.ts
Labels: Documentation, v2, size:XXL

#4464 Make accordion hook
  frontend/src/hooks/tools/shared/useAccordionSteps.ts
  frontend/src/tools/ChangeMetadata.tsx
Labels: v2, size:L

#4400 Update and improve the zh-TW Traditional Chinese translation
  app/core/src/main/resources/messages_zh_TW.properties
Labels: Translation, size:L

#4437 Feature/v2/embed pdf
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en-GB/translation.json
  frontend/src/App.tsx
  frontend/src/components/layout/Workbench.tsx
  frontend/src/components/shared/RightRail.tsx
  frontend/src/components/viewer/CustomSearchLayer.tsx
  frontend/src/components/viewer/EmbedPdfViewer.tsx
  frontend/src/components/viewer/LocalEmbedPDF.tsx
  frontend/src/components/viewer/PanAPIBridge.tsx
  frontend/src/components/viewer/PdfViewerToolbar.tsx
  frontend/src/components/viewer/RotateAPIBridge.tsx
  frontend/src/components/viewer/ScrollAPIBridge.tsx
  frontend/src/components/viewer/SearchAPIBridge.tsx
  frontend/src/components/viewer/SearchInterface.tsx
  frontend/src/components/viewer/SelectionAPIBridge.tsx
  frontend/src/components/viewer/SpreadAPIBridge.tsx
  frontend/src/components/viewer/ThumbnailAPIBridge.tsx
  frontend/src/components/viewer/ThumbnailSidebar.tsx
  frontend/src/components/viewer/Viewer.tsx
  frontend/src/components/viewer/ZoomAPIBridge.tsx
  frontend/src/components/viewer/constants/search.ts
  frontend/src/contexts/ViewerContext.tsx
  frontend/src/global.d.ts
  frontend/src/styles/theme.css
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: v2, size:XXL

#4467 Disable language selection for everything other than English GB
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/shared/LanguageSelector.tsx
Labels: v2, size:L, on-hold

#4468 Make Viewer always accessible
  frontend/src/components/shared/TopControls.tsx
  frontend/src/types/fileContext.ts
  frontend/src/types/workbench.ts
  frontend/src/utils/toolOperationTracker.ts
Labels: v2, size:L

#4471 Add Crop to V2
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/tools/crop/CropAreaSelector.tsx
  frontend/src/components/tools/crop/CropSettings.tsx
  frontend/src/components/tooltips/useCropTooltips.ts
  frontend/src/constants/cropConstants.ts
  frontend/src/constants/pageSizeConstants.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/crop/useCropOperation.ts
  frontend/src/hooks/tools/crop/useCropParameters.ts
  frontend/src/theme/mantineTheme.ts
  frontend/src/tools/Crop.tsx
  frontend/src/utils/cropCoordinates.ts
  testing/crop_test.pdf
Labels: v2, size:XXL

#4360 Update PDF.js integration and dependencies
  .github/workflows/PR-Auto-Deploy-V2.yml
  .github/workflows/frontend-licenses-update.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/public/pdf.js
  frontend/public/pdf.worker.js
  frontend/scripts/generate-licenses.js
  frontend/src/assets/3rdPartyLicenses.json
  frontend/src/global.d.ts
  frontend/src/hooks/usePDFProcessor.ts
  frontend/src/services/pdfProcessingService.ts
  frontend/src/services/pdfWorkerManager.ts
  frontend/src/utils/thumbnailUtils.ts
  frontend/vite.config.ts
  frontend/vitest.config.ts
Labels: v2, Github, size:XXL

#4496 Feature/toasts and error handling
  app/core/src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  app/core/src/main/java/stirling/software/SPDF/model/api/general/MergePdfsRequest.java
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/fileEditor/FileEditor.module.css
  frontend/src/components/fileEditor/FileEditor.tsx
  frontend/src/components/fileEditor/FileEditorThumbnail.tsx
  frontend/src/components/layout/Workbench.tsx
  frontend/src/components/shared/DismissAllErrorsButton.tsx
  frontend/src/components/shared/RainbowThemeProvider.tsx
  frontend/src/components/shared/RightRail.tsx
  frontend/src/components/toast/Toast.README.md
  frontend/src/components/toast/ToastContext.tsx
  frontend/src/components/toast/ToastRenderer.css
  frontend/src/components/toast/ToastRenderer.tsx
  frontend/src/components/toast/index.ts
  frontend/src/components/toast/types.ts
  frontend/src/contexts/file/FileReducer.ts
  frontend/src/contexts/file/fileActions.ts
  frontend/src/hooks/tools/convert/useConvertOperation.ts
  frontend/src/hooks/tools/merge/useMergeOperation.ts
  frontend/src/hooks/tools/shared/useToolApiCalls.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/services/errorUtils.ts
  frontend/src/services/http.ts
  frontend/src/services/specialErrorToasts.ts
  frontend/src/styles/theme.css
  frontend/src/tests/convert/ConvertIntegration.test.tsx
  frontend/src/theme/mantineTheme.ts
  frontend/src/types/fileContext.ts
  frontend/src/utils/toolErrorHandler.ts
  frontend/tailwind.config.js
Labels: Documentation, Java, Back End, v2, API, size:XXL

#4314 feat(multi-layout): implement form field copying and transformation for multi-page PDF to keep form data
  app/common/src/main/java/stirling/software/common/util/FormUtils.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/MultiPageLayoutController.java
  app/core/src/test/java/stirling/software/SPDF/controller/api/MultiPageLayoutControllerTest.java
Labels: enhancement, Java, Back End, API, Test, size:XL

#4487 Feature/v2/exportpdf
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/shared/RightRail.tsx
  frontend/src/components/viewer/ExportAPIBridge.tsx
  frontend/src/components/viewer/LocalEmbedPDF.tsx
  frontend/src/contexts/ViewerContext.tsx
Labels: v2, size:L

#4505 Convert extract-image-scans to React component
  app/core/src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/tools/scannerImageSplit/ScannerImageSplitSettings.tsx
  frontend/src/components/tooltips/useScannerImageSplitTips.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/scannerImageSplit/useScannerImageSplitOperation.ts
  frontend/src/hooks/tools/scannerImageSplit/useScannerImageSplitParameters.ts
  frontend/src/services/zipFileService.ts
  frontend/src/tools/ScannerImageSplit.tsx
Labels: Java, Back End, v2, API, size:L

#4501 feat: Add React-based extract-images tool
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/tools/extractImages/ExtractImagesSettings.tsx
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/extractImages/useExtractImagesOperation.ts
  frontend/src/hooks/tools/extractImages/useExtractImagesParameters.ts
  frontend/src/tools/ExtractImages.tsx
Labels: enhancement, v2, size:L

#4502 add attatchments tool
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/addAttachments/useAddAttachmentsOperation.ts
  frontend/src/hooks/tools/addAttachments/useAddAttachmentsParameters.ts
  frontend/src/tools/AddAttachments.tsx
Labels: v2, size:L

#4503 Feature/remove images
  frontend/public/locales/en-US/translation.json
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/removeImage/useRemoveImageOperation.ts
  frontend/src/hooks/tools/removeImage/useRemoveImageParameters.ts
  frontend/src/tools/RemoveImage.tsx
Labels: v2, size:L

#4516 update embedpdf
  frontend/package-lock.json
  frontend/package.json
Labels: v2, size:M

#4168 Translate fr
  app/core/src/main/resources/messages_fr_FR.properties
Labels: Translation, size:M

#4290 Spanish translation
  app/core/src/main/resources/messages_es_ES.properties
Labels: Translation, size:XL

#4401 Update Hungarian translation
  app/core/src/main/resources/messages_hu_HU.properties
Labels: Translation, size:XS

#4411 Update serbian translation
  app/core/src/main/resources/messages_sr_LATN_RS.properties
Labels: Translation, size:L

#4494 feat(replace-and-invert-colour): Add CMYK color space conversion with prepress preset for PDF processing
  app/common/src/main/java/stirling/software/common/model/api/misc/ReplaceAndInvert.java
  app/common/src/main/java/stirling/software/common/util/misc/ColorSpaceConversionStrategy.java
  app/core/src/main/java/stirling/software/SPDF/Factories/ReplaceAndInvertColorFactory.java
  app/core/src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/ReplaceAndInvertColorController.java
  app/core/src/main/java/stirling/software/SPDF/model/api/misc/ReplaceAndInvertColorRequest.java
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/templates/misc/replace-color.html
Labels: enhancement, Java, Front End, Back End, Translation, API, size:L

#4497 refactor(core,common,proprietary): Replace Date with Instant/modern Date API alternative for improved time handling
  app/common/src/main/java/stirling/software/common/model/PdfMetadata.java
  app/common/src/main/java/stirling/software/common/service/PdfMetadataService.java
  app/common/src/main/java/stirling/software/common/util/EmlParser.java
  app/common/src/main/java/stirling/software/common/util/PdfAttachmentHandler.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToPDFA.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/MetadataController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/security/ValidateSignatureController.java
  app/core/src/main/java/stirling/software/SPDF/service/AttachmentService.java
  app/core/src/test/java/stirling/software/SPDF/service/PdfMetadataServiceBasicTest.java
  app/core/src/test/java/stirling/software/SPDF/service/PdfMetadataServiceTest.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/config/AccountWebController.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/controller/web/TeamWebController.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/database/repository/JPATokenRepositoryImpl.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/database/repository/SessionRepository.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/filter/FirstLoginFilter.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/PersistentLogin.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/SessionEntity.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/JwtService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/session/SessionPersistentRegistry.java
Labels: Java, Front End, Back End, Security, API, Test, size:L, refactor

#4132 refactor: replace size checks with isEmpty(), safely collapse redundant emptiness checking logic, minor code improvements
  app/common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  app/common/src/main/java/stirling/software/common/util/CustomHtmlSanitizer.java
  app/common/src/main/java/stirling/software/common/util/PDFToFile.java
  app/common/src/main/java/stirling/software/common/util/PdfUtils.java
  app/core/src/main/java/stirling/software/SPDF/config/AppUpdateService.java
  app/core/src/main/java/stirling/software/SPDF/config/CleanUrlInterceptor.java
  app/core/src/main/java/stirling/software/SPDF/config/ExternalAppDepConfig.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/RearrangePagesPDFController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySizeController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToPDFA.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/filters/FilterController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/AutoRenameController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImageScansController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/OCRController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineDirectoryProcessor.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/security/SanitizeController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/security/WatermarkController.java
  app/core/src/main/java/stirling/software/SPDF/controller/web/GeneralWebController.java
  app/core/src/main/java/stirling/software/SPDF/service/ApiDocService.java
  app/core/src/main/java/stirling/software/SPDF/service/MetricsAggregatorService.java
Labels: Java, Front End, Back End, API, size:L, refactor

#4472 feat(cbz-to-pdf,pdf-to-cbz): Converter for CBZ format to and from PDF
  app/common/src/main/java/stirling/software/common/util/CbzUtils.java
  app/common/src/main/java/stirling/software/common/util/PdfToCbzUtils.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/converters/ConvertImgPDFController.java
  app/core/src/main/java/stirling/software/SPDF/controller/web/ConverterWebController.java
  app/core/src/main/java/stirling/software/SPDF/model/api/converters/ConvertCbzToPdfRequest.java
  app/core/src/main/java/stirling/software/SPDF/model/api/converters/ConvertPdfToCbzRequest.java
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/templates/convert/cbz-to-pdf.html
  app/core/src/main/resources/templates/convert/pdf-to-cbz.html
  app/core/src/main/resources/templates/fragments/navElements.html
  app/core/src/test/java/stirling/software/SPDF/controller/api/converters/CbzUtilsTest.java
  app/core/src/test/java/stirling/software/SPDF/controller/api/converters/PdfToCbzUtilsTest.java
Labels: enhancement, Java, Front End, Back End, Translation, API, Test, size:XL

#4520 ci(frontend): update licenses workflow dependencies and Node.js version
  .github/workflows/frontend-licenses-update.yml
Labels: v2, Github, size:S

#4522 refactor(types): deduplicate `AutomateParameters` definition in automation types
  frontend/src/types/automation.ts
Labels: v2, size:XS, refactor

#4524 feat(frontend): refactor ToolStep props handling and children usage
  frontend/src/components/tools/shared/ToolStep.tsx
Labels: enhancement, v2, size:S

#4441 feat(sign): Add signature color picker and custom signature colors
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/static/css/sign.css
  app/core/src/main/resources/static/js/pages/sign.js
  app/core/src/main/resources/static/js/sign/signature-canvas.js
  app/core/src/main/resources/templates/sign.html
Labels: enhancement, Front End, Translation, size:M, pr-deployed

#4416 Defaulting JWT settings to `false`
  app/common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  app/common/src/main/java/stirling/software/common/util/PdfUtils.java
  app/common/src/test/java/stirling/software/common/model/ApplicationPropertiesLogicTest.java
  app/core/src/main/java/stirling/software/SPDF/UI/impl/LoadingWindow.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/filters/FilterController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/MetadataController.java
  app/core/src/main/java/stirling/software/SPDF/controller/api/security/WatermarkController.java
  app/core/src/main/java/stirling/software/SPDF/controller/web/GeneralWebController.java
  app/core/src/main/resources/settings.yml.template
  app/proprietary/src/main/java/stirling/software/proprietary/security/InitialSecuritySetup.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPairCleanupService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPersistenceService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPersistenceServiceInterface.java
  app/proprietary/src/test/java/stirling/software/proprietary/security/service/KeyPersistenceServiceInterfaceTest.java
  testing/allEndpointsRemovedSettings.yml
Labels: Java, Front End, Back End, Security, API, Test, size:L

#4559 test
  .github/scripts/check_language_json.py
  .github/workflows/sync_files_v2.yml
  README.md
  frontend/public/locales/de-DE/translation.json
  frontend/public/locales/es-ES/translation.json
  frontend/public/locales/it-IT/translation.json
  frontend/public/locales/zh-CN/translation.json
  scripts/counter_translation_v2.py
Labels: Documentation, v2, Github, size:XXL
