Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-02, with the labels that each got.

#2852 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2849 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:S

#2844 checks the compatibility of the licenses
  .github/workflows/build.yml
  .github/workflows/licenses-update.yml
  allowed-licenses.json
  build.gradle
Labels: enhancement, Docker, Github, size:L

#2850 Add: Translation Support for `Sort by:` in Home Page
  src/main/resources/messages_en_GB.properties
  src/main/resources/templates/home.html
Labels: enhancement, Front End, Translation, size:XS

#2847 Fix: incorrect `setAttribute` syntax for `tooltip` `data-title`
  src/main/resources/static/js/navbar.js
Labels: Bug, Front End, size:XS

#2862 Create sonarqube.yml
  .github/workflows/sonarqube.yml
Labels: Github, size:M

#2861 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2869 Fix: wrong link `picture_as_pdf` change to `img-to-pdf` #2867
  src/main/resources/templates/home-legacy.html
Labels: Front End, size:XS, Priority: High

#2866 Update sonarqube.yml and removal of gradle keys
  .github/workflows/build.yml
  .github/workflows/sonarqube.yml
  .github/workflows/sync_files.yml
  DeveloperGuide.md
  build.gradle
  gradle/verification-keyring.gpg
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  src/main/java/stirling/software/SPDF/controller/api/AdditionalLanguageJsController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertHtmlToPDF.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertMarkdownToPdf.java
  src/main/java/stirling/software/SPDF/service/LanguageService.java
  src/main/java/stirling/software/SPDF/utils/FileToPdf.java
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
  testing/test.sh
Labels: Documentation, Java, Back End, Docker, API, Github, size:L

#2872 Update sync_files.yml
  .github/workflows/sync_files.yml
Labels: Github, size:S

#2875 Update screenshots
  images/stirling-home-dark.png
  images/stirling-home.jpg
Labels: size:XS

#2882 Pipeline fix for some features missing documentation
  build.gradle
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertHtmlToPDF.java
  src/main/java/stirling/software/SPDF/controller/api/misc/OCRController.java
Labels: Java, Back End, API, size:XS

#2884 removes remnants of verification metadata
  .github/workflows/build.yml
  .github/workflows/sync_files.yml
  testing/test.sh
Labels: Docker, Github, size:L

#2883 Fix issue #2842: Handle qpdf exit code 3 as success with warnings
  src/main/java/stirling/software/SPDF/utils/ProcessExecutor.java
Labels: Bug, Java, size:M

#2894 Homepage hotfix
  src/main/resources/templates/fragments/navElements.html
  src/main/resources/templates/home-legacy.html
Labels: Bug, Front End, size:L

#2898 Fix for tab issue
  src/main/resources/static/js/navbar.js
Labels: Bug, Front End, size:XS

#2896 PDFA fixes
  Dockerfile
  Dockerfile.fat
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToPDFA.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
Labels: Java, Back End, Docker, Translation, API, size:S

#2905 Update messages_pt_BR.properties
  src/main/resources/messages_pt_BR.properties
Labels: Translation, size:M

#2906 pipeline bug, doc bugs, auto split new URL and doc
  build.gradle
  docs/stirling-pdf.png
  docs/stirling-transparent.svg
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoSplitPdfController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImagesController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/FlattenController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/OCRController.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineController.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineDirectoryProcessor.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessor.java
  src/main/java/stirling/software/SPDF/controller/api/security/RemoveCertSignController.java
  src/main/java/stirling/software/SPDF/model/PipelineResult.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/files/Auto Splitter Divider (minimal).pdf
  src/main/resources/static/files/Auto Splitter Divider (with instructions).pdf
  src/main/resources/templates/auto-split-pdf.html
Labels: Java, Front End, Back End, Translation, API, size:L

#2890 Fix issue #2511: Fix broken ZIP issue by adding zipOut.finish()
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySectionsController.java
Labels: Bug, Java, Back End, API, size:XS

#2915 GHA/sonarqube: fix authentication
  .github/workflows/sonarqube.yml
Labels: Github, size:XS

#2919 new strings translated to sv_SE
  src/main/resources/messages_sv_SE.properties
Labels: Translation, size:L

#2909 changes in the translation `qpdf` to `libreoffice`
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:M

#2911 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2908 fix: added missing language string en_GB, sl_SI
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_sl_SI.properties
Labels: Translation, size:XS

#2937 fix(pdf): resolve compression error and file overwrite issues
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
Labels: Bug, Java, Back End, API, size:XS

#2940 fix: Allow Entry overflow when text is too long
  src/main/resources/templates/fragments/navbarEntry.html
  src/main/resources/templates/fragments/navbarEntryCustom.html
Labels: Bug, Front End, size:XS

#2925 third-party GitHubAction not pinned by hash
  .github/workflows/sonarqube.yml
Labels: Github, size:XS

#2948 Update messages_zh_CN.properties
  src/main/resources/messages_zh_CN.properties
Labels: Translation, size:S

#2957 Fix/full invert crash 2942
  src/main/java/stirling/software/SPDF/utils/misc/InvertFullColorStrategy.java
Labels: Bug, Java, size:L

#2977 Fix: Replace pull_request with pull_request_target in SonarQube Workflow for Fork Analysis
  .github/workflows/sonarqube.yml
Labels: Github, size:S

#2972 Unify translations for "rédiger" and "caviarder" with "censurer"
  src/main/resources/messages_fr_FR.properties
Labels: Translation, size:S

#2969 Translation localization
  src/main/resources/messages_zh_CN.properties
Labels: Translation, size:L

#2971 [Test PR] Desktop fix and unoconv to unoserver
  .github/workflows/PR-Demo-Comment.yml
  .github/workflows/push-docker.yml
  Dockerfile
  Dockerfile.fat
  build.gradle
  src/main/java/stirling/software/SPDF/UI/impl/DesktopBrowser.java
  src/main/java/stirling/software/SPDF/UI/impl/LoadingWindow.java
  src/main/java/stirling/software/SPDF/config/ExternalAppDepConfig.java
  src/main/java/stirling/software/SPDF/controller/api/RearrangePagesPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertOfficeController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPDF.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ExtractCSVController.java
  src/main/java/stirling/software/SPDF/model/SortTypes.java
  src/main/java/stirling/software/SPDF/model/api/PDFWithPageNums.java
  src/main/java/stirling/software/SPDF/model/api/extract/PDFFilePage.java
  src/main/java/stirling/software/SPDF/model/api/general/RearrangePagesRequest.java
  src/main/java/stirling/software/SPDF/model/api/misc/AddPageNumbersRequest.java
  src/main/java/stirling/software/SPDF/utils/FileToPdf.java
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
  src/main/java/stirling/software/SPDF/utils/UIScaling.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/js/pages/pdf-to-csv.js
  src/main/resources/templates/convert/pdf-to-csv.html
  src/main/resources/templates/pdf-organizer.html
  testing/cucumber/exampleFiles/tables.pdf
  testing/cucumber/features/external.feature
  testing/test.sh
Labels: Java, Front End, Back End, Docker, Translation, API, Github, size:XL

#2988 name change for view PDF to view/edit PDF
  README.md
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
Labels: Documentation, Translation, size:S

#2993 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#2996 Update messages_bg_BG.properties
  src/main/resources/messages_bg_BG.properties
Labels: Translation, size:L

#2991 Enhance Java Development Configuration and Code Formatting
  .vscode/extensions.json
  .vscode/settings.json
  build.gradle
Labels: enhancement, size:L

#3016 Update UserService.java to generate API key if empty
  src/main/java/stirling/software/SPDF/config/security/UserService.java
Labels: Java, Back End, Security, size:XS

#3023 Bump me.friwi:jcefmaven: from 127.3.1 to 132.3.1
  build.gradle
Labels: size:XS, Priority: Critical

#3020 Update zh_TW Traditional Chinese translation
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:S

#3005 Adding font-liberation and font-linux-libertine to fat image (#3001)
  Dockerfile.fat
Labels: enhancement, Docker, size:M

#3003 Feature/convert to grayscale
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/model/api/misc/OptimizePdfRequest.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/misc/compress-pdf.html
Labels: enhancement, Java, Front End, Back End, Translation, API, size:M

#2958 Fix: Ensure window.analyticsPromptBoolean is Defined for Analytics Dialog
  src/main/resources/templates/home.html
Labels: Bug, Front End, size:XS

#3031 Fix: Analytics Initialization Behavior
  src/main/java/stirling/software/SPDF/service/PostHogService.java
  src/main/resources/settings.yml.template
Labels: Java, Back End, size:XS

#3032 Fix showupdate
  src/main/resources/static/js/githubVersion.js
  src/main/resources/static/js/homecard.js
  src/main/resources/templates/home-legacy.html
  src/main/resources/templates/home.html
Labels: Front End, size:M

#3039 Updated spanish translations
  src/main/resources/messages_es_ES.properties
Labels: Translation, size:L

#3037 Login Language Dropdown: Remove Flag Icon
  src/main/resources/templates/login.html
Labels: Front End, size:XS

#3036 Enhance AppUpdateService: Add `@Configuration` Annotation for Improved Spring Boot Integration
  src/main/java/stirling/software/SPDF/config/AppUpdateService.java
Labels: enhancement, Java, Back End, size:XS

#3042 dynamic port for UI from 8080 up (8081 etc)
  src/main/java/stirling/software/SPDF/SPDFApplication.java
  src/main/java/stirling/software/SPDF/config/RuntimePathConfig.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/utils/UrlUtils.java
  src/test/java/stirling/software/SPDF/SPDFApplicationTest.java
Labels: Java, Back End, API, size:M

#3048 move `compress.grayscale.label` to section `#compress`
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:M

#3061 Restrict Backup Import to Initialization Process and Refactor API Key Handling
  src/main/java/stirling/software/SPDF/config/security/InitialSecuritySetup.java
  src/main/java/stirling/software/SPDF/config/security/UserService.java
Labels: Java, Back End, Security, size:S

#3055 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3041 Refactor Path Handling
  src/main/java/stirling/software/SPDF/SPDFApplication.java
  src/main/java/stirling/software/SPDF/config/InstallationPathConfig.java
  src/main/java/stirling/software/SPDF/config/RuntimePathConfig.java
  src/main/java/stirling/software/SPDF/config/security/database/DatabaseConfig.java
  src/main/java/stirling/software/SPDF/controller/web/GeneralWebController.java
  src/main/java/stirling/software/SPDF/utils/FileMonitor.java
Labels: Java, Front End, Back End, Security, size:L

#2990 Improve Type-Safe Casting with Pattern Matching
  src/main/java/stirling/software/SPDF/config/security/CustomLogoutSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/IPRateLimitingFilter.java
  src/main/java/stirling/software/SPDF/config/security/UserAuthenticationFilter.java
  src/main/java/stirling/software/SPDF/config/security/UserService.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/oauth2/OAuth2Configuration.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CertificateUtils.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2AuthenticatedPrincipal.java
  src/main/java/stirling/software/SPDF/config/security/saml2/CustomSaml2AuthenticationSuccessHandler.java
  src/main/java/stirling/software/SPDF/config/security/session/SessionPersistentRegistry.java
  src/main/java/stirling/software/SPDF/controller/api/UserController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoSplitPdfController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessor.java
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  src/main/java/stirling/software/SPDF/controller/api/security/SanitizeController.java
  src/main/java/stirling/software/SPDF/controller/web/AccountWebController.java
  src/main/java/stirling/software/SPDF/model/provider/GitHubProvider.java
  src/main/java/stirling/software/SPDF/model/provider/GoogleProvider.java
  src/main/java/stirling/software/SPDF/model/provider/KeycloakProvider.java
  src/main/java/stirling/software/SPDF/service/CertificateValidationService.java
  src/main/java/stirling/software/SPDF/utils/ImageProcessingUtils.java
  src/test/java/stirling/software/SPDF/config/security/CustomLogoutSuccessHandlerTest.java
  src/test/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPdfTest.java
  src/test/java/stirling/software/SPDF/utils/validation/ValidatorTest.java
Labels: enhancement, Java, Front End, Back End, Security, API, size:L

#3052 add view pdf to nav and remove duplicate home on view
  build.gradle
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/view-pdf.html
Labels: Front End, size:S

#3065 Remove book
  build.gradle
  src/main/resources/templates/fragments/navElements.html
  src/main/resources/templates/home-legacy.html
Labels: Front End, size:S

#3067 Improve Case-Insensitive Key Comparison and Path Normalization in Language Properties Check Script
  .github/scripts/check_language_properties.py
Labels: enhancement, Github, size:S

#3072 Remove `convertBookTypeToPdf` and Improve File Sanitization in `FileToPdf`
  src/main/java/stirling/software/SPDF/utils/FileToPdf.java
  src/main/java/stirling/software/SPDF/utils/ProcessExecutor.java
  src/test/java/stirling/software/SPDF/utils/FileToPdfTest.java
Labels: Java, size:L

#3071 Update survey version cache
  src/main/resources/static/js/pages/home.js
Labels: Front End, size:XS

#3079 Add description to search. Fix homepage broken by )
  src/main/resources/static/js/homecard.js
  src/main/resources/static/js/pages/home.js
Labels: Front End, size:XS

#3078 Remove book site and translation entries
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/templates/convert/book-to-pdf.html
  src/main/resources/templates/convert/pdf-to-book.html
Labels: Java, Front End, Back End, Translation, size:L

#3081 Compression fixes
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/misc/compress-pdf.html
Labels: Java, Front End, Back End, Translation, API, size:XL

#3074 lang: update fr_FR
  src/main/resources/messages_fr_FR.properties
Labels: Translation, size:S
