Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-08, with the labels that each got.

#4070 Support for SSL testing
  .github/workflows/PR-Auto-Deploy-V2.yml
Labels: Github, size:XS

#4087 Fix GB language file
  frontend/public/locales/en-GB/translation.json
Labels: size:XS, Bugfix

#4100 Update zh_TW Traditional Chinese translation
  app/core/src/main/resources/messages_zh_TW.properties
Labels: Translation, size:XS

#4099 fix(stamp): validate image filename only for image stamp type
  app/core/src/main/java/stirling/software/SPDF/controller/api/misc/StampController.java
Labels: Java, Back End, API, size:S, Bugfix

#4094 Updated Hungarian translation
  app/core/src/main/resources/messages_hu_HU.properties
Labels: Translation, size:XS

#4078 Added structure for filemanager
  frontend/src/App.tsx
  frontend/src/components/fileEditor/FileEditor.tsx
  frontend/src/components/shared/FileUploadModal.tsx
  frontend/src/components/shared/LandingPage.tsx
  frontend/src/components/shared/QuickAccessBar.tsx
  frontend/src/components/tools/convert/ConvertSettings.tsx
  frontend/src/contexts/FilesModalContext.tsx
  frontend/src/hooks/useFileHandler.ts
  frontend/src/hooks/useFilesModal.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/tests/convert/ConvertE2E.spec.ts
Labels: size:L

#4129 feat(common): add configurable maxDPI limit for PDF-to-image conversion
  app/common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  app/common/src/main/java/stirling/software/common/util/PdfUtils.java
  app/core/src/main/java/stirling/software/SPDF/controller/web/ConverterWebController.java
  app/core/src/main/resources/messages_ar_AR.properties
  app/core/src/main/resources/messages_az_AZ.properties
  app/core/src/main/resources/messages_bg_BG.properties
  app/core/src/main/resources/messages_bo_CN.properties
  app/core/src/main/resources/messages_ca_CA.properties
  app/core/src/main/resources/messages_cs_CZ.properties
  app/core/src/main/resources/messages_da_DK.properties
  app/core/src/main/resources/messages_de_DE.properties
  app/core/src/main/resources/messages_el_GR.properties
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/messages_en_US.properties
  app/core/src/main/resources/messages_es_ES.properties
  app/core/src/main/resources/messages_eu_ES.properties
  app/core/src/main/resources/messages_fa_IR.properties
  app/core/src/main/resources/messages_fr_FR.properties
  app/core/src/main/resources/messages_ga_IE.properties
  app/core/src/main/resources/messages_hi_IN.properties
  app/core/src/main/resources/messages_hr_HR.properties
  app/core/src/main/resources/messages_hu_HU.properties
  app/core/src/main/resources/messages_id_ID.properties
  app/core/src/main/resources/messages_it_IT.properties
  app/core/src/main/resources/messages_ja_JP.properties
  app/core/src/main/resources/messages_ko_KR.properties
  app/core/src/main/resources/messages_ml_IN.properties
  app/core/src/main/resources/messages_nl_NL.properties
  app/core/src/main/resources/messages_no_NB.properties
  app/core/src/main/resources/messages_pl_PL.properties
  app/core/src/main/resources/messages_pt_BR.properties
  app/core/src/main/resources/messages_pt_PT.properties
  app/core/src/main/resources/messages_ro_RO.properties
  app/core/src/main/resources/messages_ru_RU.properties
  app/core/src/main/resources/messages_sk_SK.properties
  app/core/src/main/resources/messages_sl_SI.properties
  app/core/src/main/resources/messages_sr_LATN_RS.properties
  app/core/src/main/resources/messages_sv_SE.properties
  app/core/src/main/resources/messages_th_TH.properties
  app/core/src/main/resources/messages_tr_TR.properties
  app/core/src/main/resources/messages_uk_UA.properties
  app/core/src/main/resources/messages_vi_VN.properties
  app/core/src/main/resources/messages_zh_CN.properties
  app/core/src/main/resources/messages_zh_TW.properties
  app/core/src/main/resources/settings.yml.template
  app/core/src/main/resources/templates/convert/pdf-to-img.html
  devGuide/DeveloperGuide.md
Labels: Documentation, enhancement, Java, Front End, Back End, Translation, size:M, Devtools, pr-deployed

#4142 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Github, size:S

#4112 Feature/v2/tooltips
  frontend/public/logo-tooltip.svg
  frontend/src/components/shared/QuickAccessBar.tsx
  frontend/src/components/shared/Tooltip.tsx
  frontend/src/components/shared/tooltip/Tooltip.README.md
  frontend/src/components/shared/tooltip/Tooltip.module.css
  frontend/src/components/shared/tooltip/TooltipContent.tsx
  frontend/src/components/tools/shared/ToolStep.tsx
  frontend/src/components/tooltips/CompressTips.ts
  frontend/src/components/tooltips/OCRTips.ts
  frontend/src/contexts/SidebarContext.tsx
  frontend/src/hooks/useTooltipPosition.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/styles/theme.css
  frontend/src/tools/Compress.tsx
  frontend/src/tools/OCR.tsx
  frontend/src/types/sidebar.ts
  frontend/src/types/tips.ts
  frontend/src/utils/genericUtils.ts
  frontend/src/utils/sidebarUtils.ts
Labels: Documentation, v2, size:XXL

#4092 chore(templates): remove redundant `fetch-utils.js` script includes
  app/core/src/main/resources/templates/home-legacy.html
  app/core/src/main/resources/templates/home.html
  app/core/src/main/resources/templates/misc/scanner-effect.html
  app/core/src/main/resources/templates/misc/show-javascript.html
  app/core/src/main/resources/templates/pipeline.html
  app/core/src/main/resources/templates/security/get-info-on-pdf.html
Labels: Front End, size:XS, chore, pr-deployed

#4130 chore: update development configs, formatting tools, and CI enhancements
  .devcontainer/devcontainer.json
  .editorconfig
  .github/config/.files.yaml
  .github/labels.yml
  .vscode/settings.json
  build.gradle
Labels: Github, size:M, Devtools, chore, Gradle

#4065 refactor(eml-to-pdf): Improve readability, maintainability, and overall standards compliance
  app/common/src/main/java/stirling/software/common/util/EmlParser.java
  app/common/src/main/java/stirling/software/common/util/EmlProcessingUtils.java
  app/common/src/main/java/stirling/software/common/util/EmlToPdf.java
  app/common/src/main/java/stirling/software/common/util/PdfAttachmentHandler.java
Labels: Java, size:XXL, refactor, pr-deployed

#4124 get updates advanced
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/static/js/githubVersion.js
  app/core/src/main/resources/templates/fragments/navbar.html
  build.gradle
Labels: Front End, Translation, size:L, Gradle, pr-deployed

#4121 Feature/v2/filemanager
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/FileManager.tsx
  frontend/src/components/fileManagement/StorageStatsCard.tsx
  frontend/src/components/fileManager/CompactFileDetails.tsx
  frontend/src/components/fileManager/DesktopLayout.tsx
  frontend/src/components/fileManager/DragOverlay.tsx
  frontend/src/components/fileManager/FileDetails.tsx
  frontend/src/components/fileManager/FileInfoCard.tsx
  frontend/src/components/fileManager/FileListArea.tsx
  frontend/src/components/fileManager/FileListItem.tsx
  frontend/src/components/fileManager/FilePreview.tsx
  frontend/src/components/fileManager/FileSourceButtons.tsx
  frontend/src/components/fileManager/HiddenFileInput.tsx
  frontend/src/components/fileManager/MobileLayout.tsx
  frontend/src/components/fileManager/SearchInput.tsx
  frontend/src/components/shared/FileCard.tsx
  frontend/src/components/shared/FileGrid.tsx
  frontend/src/components/shared/FileUploadModal.tsx
  frontend/src/components/shared/FileUploadSelector.tsx
  frontend/src/contexts/FileContext.tsx
  frontend/src/contexts/FileManagerContext.tsx
  frontend/src/contexts/FilesModalContext.tsx
  frontend/src/hooks/tools/convert/useConvertOperation.ts
  frontend/src/hooks/useFileManager.ts
  frontend/src/hooks/useFilesModal.ts
  frontend/src/hooks/useIndexedDBThumbnail.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/services/fileStorage.ts
  frontend/src/styles/theme.css
  frontend/src/tests/convert/ConvertIntegration.test.tsx
  frontend/src/tests/convert/ConvertSmartDetectionIntegration.test.tsx
  frontend/src/utils/fileUtils.ts
  frontend/src/utils/thumbnailUtils.ts
Labels: v2, size:XXL

#4149 Enforce 2 space indentation in editorconfig
  .editorconfig
Labels: size:XS, Devtools

#4138 V2 Restructure homepage
  frontend/src/components/layout/Workbench.tsx
  frontend/src/components/shared/QuickAccessBar.tsx
  frontend/src/components/tools/ToolPanel.tsx
  frontend/src/components/tools/ToolPicker.tsx
  frontend/src/contexts/ToolWorkflowContext.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/types/sidebar.ts
Labels: v2, size:XL

#4134 Feature/v2/shared tool hooks
  CLAUDE.md
  frontend/src/components/tools/split/SplitSettings.tsx
  frontend/src/hooks/tools/compress/useCompressOperation.ts
  frontend/src/hooks/tools/convert/useConvertOperation.ts
  frontend/src/hooks/tools/ocr/useOCROperation.ts
  frontend/src/hooks/tools/shared/useToolApiCalls.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/hooks/tools/shared/useToolResources.ts
  frontend/src/hooks/tools/shared/useToolState.ts
  frontend/src/hooks/tools/split/useSplitOperation.ts
  frontend/src/hooks/tools/split/useSplitParameters.ts
  frontend/src/services/enhancedPDFProcessingService.ts
  frontend/src/tests/convert/ConvertIntegration.test.tsx
  frontend/src/tools/Split.tsx
  frontend/src/types/processing.ts
  frontend/src/utils/toolErrorHandler.ts
  frontend/src/utils/toolOperationTracker.ts
  frontend/src/utils/toolResponseProcessor.ts
Labels: Documentation, v2, size:XXL

#4154 Update messages_it_IT.properties
  app/core/src/main/resources/messages_it_IT.properties
Labels: Translation, size:M

#4158 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Github, size:S

#4157 fix(saml): correct ClassPathResource handling for IdP metadata and add null-guard for privateKey
  app/common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  app/common/src/test/java/stirling/software/common/model/ApplicationPropertiesDynamicYamlPropertySourceTest.java
  app/common/src/test/java/stirling/software/common/model/ApplicationPropertiesLogicTest.java
  app/common/src/test/java/stirling/software/common/model/ApplicationPropertiesSaml2HttpTest.java
  app/common/src/test/java/stirling/software/common/model/ApplicationPropertiesSaml2ResourceTest.java
  app/common/src/test/resources/saml/dummy.txt
  build.gradle
Labels: Java, Test, size:L, Bugfix, Gradle

#4152 Update Hungarian translation for new update related strings
  app/core/src/main/resources/messages_hu_HU.properties
Labels: Translation, size:M

#4172 chore(labeler): add new 'v2' label and expand matching rules
  .github/labeler-config-srvaroa.yml
  .github/labels.yml
Labels: Github, size:XS, chore

#3921 JWT Authentication
  .claude/settings.local.json
  .github/workflows/build.yml
  app/common/src/main/java/stirling/software/common/configuration/AppConfig.java
  app/common/src/main/java/stirling/software/common/configuration/InstallationPathConfig.java
  app/common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  app/common/src/main/java/stirling/software/common/util/RequestUriUtils.java
  app/core/src/main/resources/application.properties
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/settings.yml.template
  app/core/src/main/resources/static/js/DecryptFiles.js
  app/core/src/main/resources/static/js/downloader.js
  app/core/src/main/resources/static/js/fetch-utils.js
  app/core/src/main/resources/static/js/jwt-init.js
  app/core/src/main/resources/static/js/navbar.js
  app/core/src/main/resources/static/js/usage.js
  app/core/src/main/resources/templates/account.html
  app/proprietary/build.gradle
  app/proprietary/src/main/java/stirling/software/proprietary/security/CustomAuthenticationSuccessHandler.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/CustomLogoutSuccessHandler.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/InitialSecuritySetup.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/JwtAuthenticationEntryPoint.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/config/AccountWebController.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/configuration/CacheConfig.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/configuration/SecurityConfiguration.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/filter/JwtAuthenticationFilter.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/filter/UserAuthenticationFilter.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/AuthenticationType.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/Authority.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/JwtVerificationKey.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/User.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/model/exception/AuthenticationFailureException.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/oauth2/CustomOAuth2AuthenticationSuccessHandler.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/oauth2/OAuth2Configuration.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/saml2/CustomSaml2AuthenticationSuccessHandler.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/saml2/JwtSaml2AuthenticationRequestRepository.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/saml2/Saml2Configuration.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/CustomOAuth2UserService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/CustomUserDetailsService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/JwtService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/JwtServiceInterface.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPairCleanupService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPersistenceService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPersistenceServiceInterface.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/UserService.java
  app/proprietary/src/main/resources/static/js/audit/dashboard.js
  app/proprietary/src/test/java/stirling/software/proprietary/security/CustomLogoutSuccessHandlerTest.java
  app/proprietary/src/test/java/stirling/software/proprietary/security/JwtAuthenticationEntryPointTest.java
  app/proprietary/src/test/java/stirling/software/proprietary/security/filter/JwtAuthenticationFilterTest.java
  app/proprietary/src/test/java/stirling/software/proprietary/security/saml2/JwtSaml2AuthenticationRequestRepositoryTest.java
  app/proprietary/src/test/java/stirling/software/proprietary/security/service/JwtServiceTest.java
  app/proprietary/src/test/java/stirling/software/proprietary/security/service/KeyPersistenceServiceInterfaceTest.java
  exampleYmlFiles/test_cicd.yml
Labels: Java, Front End, Back End, Docker, Translation, Security, Test, Github, size:XL, Gradle, pr-deployed

#4171 Neaten garbage collection code
  frontend/src/contexts/FileContext.tsx
  frontend/src/services/enhancedPDFProcessingService.ts
Labels: v2, size:S

#4123 Add Sanitize UI
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/tools/sanitize/SanitizeSettings.test.tsx
  frontend/src/components/tools/sanitize/SanitizeSettings.tsx
  frontend/src/hooks/tools/compress/useCompressOperation.ts
  frontend/src/hooks/tools/convert/useConvertOperation.ts
  frontend/src/hooks/tools/ocr/useOCROperation.ts
  frontend/src/hooks/tools/sanitize/useSanitizeOperation.ts
  frontend/src/hooks/tools/sanitize/useSanitizeParameters.test.ts
  frontend/src/hooks/tools/sanitize/useSanitizeParameters.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/hooks/tools/split/useSplitOperation.ts
  frontend/src/hooks/tools/split/useSplitParameters.ts
  frontend/src/hooks/useToolManagement.tsx
  frontend/src/tools/Convert.tsx
  frontend/src/tools/Sanitize.tsx
  frontend/src/types/fileContext.ts
Labels: v2, size:XL

#4203 Update manifest.json
  frontend/public/manifest.json
Labels: size:XS

#4211 Seo v2 add home
  .github/workflows/PR-Auto-Deploy-V2.yml
  .github/workflows/deploy-on-v2-commit.yml
  frontend/public/og_images/home.png
  frontend/src/pages/HomePage.tsx
Labels: Github, size:XS

#4212 Bug/v2/reduce console pollution
  .claude/settings.local.json
  frontend/index.html
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/components/FileManager.tsx
  frontend/src/components/fileEditor/FileEditor.tsx
  frontend/src/components/fileManager/HiddenFileInput.tsx
  frontend/src/components/shared/LandingPage.tsx
  frontend/src/hooks/useToolManagement.tsx
  frontend/src/i18n.ts
Labels: v2, size:L

#4196 V2 results flow
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/fileManager/FileDetails.tsx
  frontend/src/components/fileManager/FilePreview.tsx
  frontend/src/components/pageEditor/FileThumbnail.tsx
  frontend/src/components/shared/FilePreview.tsx
  frontend/src/components/shared/filePreview/DocumentStack.tsx
  frontend/src/components/shared/filePreview/DocumentThumbnail.tsx
  frontend/src/components/shared/filePreview/HoverOverlay.tsx
  frontend/src/components/shared/filePreview/NavigationArrows.tsx
  frontend/src/components/tools/ToolPanel.tsx
  frontend/src/components/tools/compress/CompressSettings.tsx
  frontend/src/components/tools/shared/FileMetadata.tsx
  frontend/src/components/tools/shared/FileStatusIndicator.tsx
  frontend/src/components/tools/shared/FilesToolStep.tsx
  frontend/src/components/tools/shared/NavigationControls.tsx
  frontend/src/components/tools/shared/OperationButton.tsx
  frontend/src/components/tools/shared/ResultsPreview.tsx
  frontend/src/components/tools/shared/ReviewToolStep.tsx
  frontend/src/components/tools/shared/SuggestedToolsSection.tsx
  frontend/src/components/tools/shared/ToolStep.tsx
  frontend/src/components/tools/shared/createToolFlow.tsx
  frontend/src/contexts/FileContext.tsx
  frontend/src/contexts/FileSelectionContext.tsx
  frontend/src/contexts/ToolWorkflowContext.tsx
  frontend/src/hooks/tools/ocr/useOCROperation.ts
  frontend/src/hooks/tools/shared/useToolApiCalls.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/hooks/useSuggestedTools.ts
  frontend/src/tools/AddPassword.tsx
  frontend/src/tools/ChangePermissions.tsx
  frontend/src/tools/Compress.tsx
  frontend/src/tools/Convert.tsx
  frontend/src/tools/Merge.tsx
  frontend/src/tools/OCR.tsx
  frontend/src/tools/Sanitize.tsx
  frontend/src/tools/Split.tsx
  frontend/src/tools/SwaggerUI.tsx
  frontend/src/types/fileContext.ts
  frontend/src/types/tool.ts
Labels: v2, size:XXL

#4215 Feature/v2/watermark
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/shared/FileUploadButton.tsx
  frontend/src/components/shared/Tooltip.tsx
  frontend/src/components/shared/tooltip/TooltipContent.tsx
  frontend/src/components/tools/addWatermark/WatermarkFormatting.tsx
  frontend/src/components/tools/addWatermark/WatermarkImageFile.tsx
  frontend/src/components/tools/addWatermark/WatermarkStyleSettings.tsx
  frontend/src/components/tools/addWatermark/WatermarkTextStyle.tsx
  frontend/src/components/tools/addWatermark/WatermarkTypeSettings.tsx
  frontend/src/components/tools/addWatermark/WatermarkWording.tsx
  frontend/src/components/tools/shared/NumberInputWithUnit.tsx
  frontend/src/components/tools/shared/ReviewToolStep.tsx
  frontend/src/components/tools/shared/ToolStep.tsx
  frontend/src/components/tools/shared/createToolFlow.tsx
  frontend/src/components/tooltips/useWatermarkTips.ts
  frontend/src/constants/addWatermarkConstants.ts
  frontend/src/hooks/tools/addWatermark/useAddWatermarkOperation.ts
  frontend/src/hooks/tools/addWatermark/useAddWatermarkParameters.ts
  frontend/src/hooks/useToolManagement.tsx
  frontend/src/tools/AddWatermark.tsx
  frontend/src/types/fileContext.ts
  frontend/src/types/tips.ts
  frontend/src/utils/textUtils.ts
Labels: v2, size:XXL

#4151 Feature/v2/all tools sidebar
  frontend/public/branding/StirlingPDFLogoNoTextDark.svg
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/layout/Workbench.tsx
  frontend/src/components/shared/AllToolsNavButton.tsx
  frontend/src/components/shared/FitText.tsx
  frontend/src/components/shared/QuickAccessBar.tsx
  frontend/src/components/shared/RainbowThemeProvider.tsx
  frontend/src/components/shared/TextInput.tsx
  frontend/src/components/shared/Tooltip.tsx
  frontend/src/components/shared/fitText/FitText.README.md
  frontend/src/components/shared/fitText/textFit.ts
  frontend/src/components/shared/quickAccessBar/ActiveToolButton.tsx
  frontend/src/components/shared/quickAccessBar/QuickAccessBar.css
  frontend/src/components/shared/quickAccessBar/QuickAccessBar.ts
  frontend/src/components/shared/textInput/TextInput.module.css
  frontend/src/components/shared/tooltip/Tooltip.README.md
  frontend/src/components/shared/tooltip/Tooltip.module.css
  frontend/src/components/tools/SearchResults.tsx
  frontend/src/components/tools/ToolPanel.tsx
  frontend/src/components/tools/ToolPicker.tsx
  frontend/src/components/tools/ToolRenderer.tsx
  frontend/src/components/tools/convert/ConvertSettings.tsx
  frontend/src/components/tools/shared/NoToolsFound.tsx
  frontend/src/components/tools/shared/SubcategoryHeader.tsx
  frontend/src/components/tools/toolPicker/ToolButton.tsx
  frontend/src/components/tools/toolPicker/ToolPicker.css
  frontend/src/components/tools/toolPicker/ToolSearch.tsx
  frontend/src/contexts/ToolWorkflowContext.tsx
  frontend/src/data/toolsTaxonomy.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/global.d.ts
  frontend/src/hooks/usePdfSignatureDetection.ts
  frontend/src/hooks/useRainbowTheme.ts
  frontend/src/hooks/useToolManagement.tsx
  frontend/src/hooks/useToolSections.ts
  frontend/src/index.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/styles/theme.css
  frontend/src/types/sidebar.ts
  frontend/src/types/tool.ts
Labels: Documentation, v2, size:XXL

#4234 V2 Repair tool
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/tools/repair/RepairSettings.tsx
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/repair/useRepairOperation.ts
  frontend/src/hooks/tools/repair/useRepairParameters.ts
  frontend/src/hooks/tools/shared/useBaseParameters.ts
  frontend/src/tools/Repair.tsx
  frontend/src/types/fileContext.ts
  frontend/src/types/parameters.ts
Labels: v2, size:L

#4237 V2 Unlock forms
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/tools/unlockPdfForms/UnlockPdfFormsSettings.tsx
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/unlockPdfForms/useUnlockPdfFormsOperation.ts
  frontend/src/hooks/tools/unlockPdfForms/useUnlockPdfFormsParameters.ts
  frontend/src/tools/UnlockPdfForms.tsx
  frontend/src/types/fileContext.ts
Labels: v2, size:L

#4242 tooltip
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/tooltips/usePageSelectionTips.tsx
Labels: v2, size:L

#4216 fix(h2): refine SQL condition check for custom database flag
  app/proprietary/src/main/java/stirling/software/proprietary/security/database/H2SQLCondition.java
Labels: Java, Security, size:XS, Bugfix

#4213 feat(common,core,proprietary): remove unused injections, enhance type safety, and improve test mocks
  app/common/src/main/java/stirling/software/common/aop/AutoJobAspect.java
  app/common/src/main/java/stirling/software/common/model/FileInfo.java
  app/common/src/main/java/stirling/software/common/model/PdfMetadata.java
  app/common/src/main/java/stirling/software/common/service/JobExecutorService.java
  app/common/src/main/java/stirling/software/common/util/CustomHtmlSanitizer.java
  app/common/src/test/java/stirling/software/common/annotations/AutoJobPostMappingIntegrationTest.java
  app/common/src/test/java/stirling/software/common/util/EmlToPdfTest.java
  app/core/src/main/java/stirling/software/SPDF/SPDFApplication.java
  app/core/src/main/java/stirling/software/SPDF/config/EndpointInspector.java
  app/core/src/main/java/stirling/software/SPDF/model/SignatureFile.java
  app/core/src/main/java/stirling/software/SPDF/service/MetricsAggregatorService.java
  app/core/src/test/java/stirling/software/SPDF/controller/api/EditTableOfContentsControllerTest.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/controller/api/AdminSettingsController.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/filter/UserAuthenticationFilter.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/JwtService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPairCleanupService.java
  app/proprietary/src/main/java/stirling/software/proprietary/security/service/KeyPersistenceService.java
  app/proprietary/src/test/java/stirling/software/proprietary/security/service/UserServiceTest.java
Labels: enhancement, Java, Back End, Security, API, Test, size:L

#4243 Feature/v2/filemanagerimprovements
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/fileManager/DesktopLayout.tsx
  frontend/src/components/fileManager/FileActions.tsx
  frontend/src/components/fileManager/FileListArea.tsx
  frontend/src/components/fileManager/FileListItem.tsx
  frontend/src/components/fileManager/MobileLayout.tsx
  frontend/src/contexts/FileManagerContext.tsx
  frontend/src/theme/mantineTheme.ts
  frontend/src/utils/downloadUtils.ts
Labels: v2, size:XL

#4246 V2 reduce boilerplate in param hooks
  frontend/src/components/tools/compress/CompressSettings.tsx
  frontend/src/components/tools/ocr/AdvancedOCRSettings.tsx
  frontend/src/components/tools/ocr/OCRSettings.tsx
  frontend/src/constants/addWatermarkConstants.ts
  frontend/src/hooks/tools/addPassword/useAddPasswordParameters.ts
  frontend/src/hooks/tools/addWatermark/useAddWatermarkParameters.ts
  frontend/src/hooks/tools/changePermissions/useChangePermissionsParameters.ts
  frontend/src/hooks/tools/compress/useCompressOperation.ts
  frontend/src/hooks/tools/compress/useCompressParameters.ts
  frontend/src/hooks/tools/convert/useConvertParameters.test.ts
  frontend/src/hooks/tools/convert/useConvertParameters.ts
  frontend/src/hooks/tools/ocr/useOCROperation.ts
  frontend/src/hooks/tools/ocr/useOCRParameters.ts
  frontend/src/hooks/tools/removePassword/useRemovePasswordParameters.ts
  frontend/src/hooks/tools/sanitize/useSanitizeParameters.ts
  frontend/src/hooks/tools/shared/useBaseParameters.ts
  frontend/src/hooks/tools/split/useSplitParameters.ts
  frontend/src/tests/convert/ConvertSmartDetectionIntegration.test.tsx
Labels: v2, size:XL

#4250 V2 hide incomplete tools
  frontend/public/locales/en-GB/translation.json
  frontend/src/data/toolsTaxonomy.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/useToolManagement.tsx
Labels: v2, size:L

#4252 V2 Fix subcategory names in All Tools (and search) pane
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/shared/QuickAccessBar.tsx
  frontend/src/components/tools/SearchResults.tsx
  frontend/src/components/tools/ToolPicker.tsx
  frontend/src/components/tools/shared/SuggestedToolsSection.tsx
  frontend/src/components/tools/toolPicker/ToolButton.tsx
  frontend/src/contexts/ToolWorkflowContext.tsx
  frontend/src/data/toolsTaxonomy.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/useSuggestedTools.ts
  frontend/src/hooks/useToolManagement.tsx
  frontend/src/hooks/useToolSections.ts
Labels: v2, size:XL

#4264 refactor(tests): move & expand TextFinder/RedactController tests; fix TextFinder empty search-term handling; update token filtering API
  app/core/src/main/java/stirling/software/SPDF/pdf/TextFinder.java
  app/core/src/test/java/stirling/software/SPDF/controller/api/security/RedactControllerTest.java
  app/core/src/test/java/stirling/software/SPDF/pdf/TextFinderTest.java
Labels: Java, Test, size:XL, Bugfix, refactor

#4274 Update messages_tr_TR.properties
  app/core/src/main/resources/messages_tr_TR.properties
Labels: Translation, size:XL

#4204 fix(i18n): standardize `{filename}` placeholder in `addPageNumbers.customNumberDesc` across all translations
  app/core/src/main/resources/messages_ar_AR.properties
  app/core/src/main/resources/messages_az_AZ.properties
  app/core/src/main/resources/messages_bg_BG.properties
  app/core/src/main/resources/messages_da_DK.properties
  app/core/src/main/resources/messages_el_GR.properties
  app/core/src/main/resources/messages_en_GB.properties
  app/core/src/main/resources/messages_en_US.properties
  app/core/src/main/resources/messages_es_ES.properties
  app/core/src/main/resources/messages_ga_IE.properties
  app/core/src/main/resources/messages_hr_HR.properties
  app/core/src/main/resources/messages_id_ID.properties
  app/core/src/main/resources/messages_it_IT.properties
  app/core/src/main/resources/messages_nl_NL.properties
  app/core/src/main/resources/messages_no_NB.properties
  app/core/src/main/resources/messages_pl_PL.properties
  app/core/src/main/resources/messages_pt_BR.properties
  app/core/src/main/resources/messages_pt_PT.properties
  app/core/src/main/resources/messages_ro_RO.properties
  app/core/src/main/resources/messages_sk_SK.properties
  app/core/src/main/resources/messages_sl_SI.properties
  app/core/src/main/resources/messages_sr_LATN_RS.properties
  app/core/src/main/resources/messages_sv_SE.properties
  app/core/src/main/resources/messages_tr_TR.properties
  app/core/src/main/resources/messages_vi_VN.properties
Labels: Translation, size:M, Bugfix

#4164 Update and improve the zh-TW Traditional Chinese translation
  app/core/src/main/resources/messages_zh_TW.properties
Labels: Translation, size:M

#4192 fix(downloader): reset progress bar after completion
  app/core/src/main/resources/static/js/downloader.js
Labels: Front End, size:XS, Bugfix, pr-deployed

#4170 build(gradle): include all subprojects in license report generation
  .github/workflows/build.yml
  .github/workflows/licenses-update.yml
  build.gradle
Labels: Docker, Github, size:S, Gradle, build

#4166 fix(config): recreate settings.yml if missing or below minimal size threshold
  app/common/src/main/java/stirling/software/common/configuration/ConfigInitializer.java
Labels: Java, size:S, Bugfix

#4173 deps: Pin Python dev dependencies and lock hashes to remediate security alert 302
  .github/scripts/requirements_dev.in
  .github/scripts/requirements_dev.txt
  Dockerfile.dev
Labels: dependencies, Docker, Github, size:XL, Devtools, pr-deployed

#4191 feat(ssrf): enhance private IP detection and IPv6 handling
  app/common/src/main/java/stirling/software/common/service/SsrfProtectionService.java
Labels: enhancement, Java, size:M

#4255 Feature/v2/right rail
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/App.tsx
  frontend/src/components/fileEditor/FileEditor.tsx
  frontend/src/components/layout/Workbench.tsx
  frontend/src/components/pageEditor/BulkSelectionPanel.tsx
  frontend/src/components/pageEditor/FileThumbnail.tsx
  frontend/src/components/pageEditor/PageEditor.tsx
  frontend/src/components/pageEditor/PageEditorControls.tsx
  frontend/src/components/pageEditor/PageThumbnail.tsx
  frontend/src/components/shared/LanguageSelector.tsx
  frontend/src/components/shared/RightRail.tsx
  frontend/src/components/shared/Tooltip.tsx
  frontend/src/components/shared/TopControls.tsx
  frontend/src/components/shared/rightRail/RightRail.README.md
  frontend/src/components/shared/rightRail/RightRail.css
  frontend/src/components/shared/tooltip/Tooltip.module.css
  frontend/src/components/tools/ToolPicker.tsx
  frontend/src/contexts/RightRailContext.tsx
  frontend/src/hooks/useRightRailButtons.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/services/pdfExportService.ts
  frontend/src/styles/theme.css
  frontend/src/types/rightRail.ts
Labels: Documentation, v2, size:XXL

#4260 Preview file
  frontend/src/contexts/ToolWorkflowContext.tsx
  frontend/src/tools/Automate.tsx
Labels: v2, size:S

#4281 AutomateFixes
  frontend/src/components/shared/TextInput.tsx
  frontend/src/components/tools/automate/AutomationCreation.tsx
  frontend/src/components/tools/automate/ToolList.tsx
  frontend/src/components/tools/automate/ToolSelector.tsx
  frontend/src/components/tools/toolPicker/ToolButton.tsx
  frontend/src/components/tools/toolPicker/ToolPicker.css
  frontend/src/components/tools/toolPicker/ToolSearch.tsx
  frontend/src/hooks/tools/automate/useAutomationForm.ts
  frontend/src/tools/Automate.tsx
  frontend/src/types/automation.ts
Labels: v2, size:L

#4292 Automation tolltip + new operations + copy to saved
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/tools/automate/AutomationEntry.tsx
  frontend/src/components/tools/automate/AutomationSelection.tsx
  frontend/src/hooks/tools/automate/useSavedAutomations.ts
  frontend/src/hooks/tools/automate/useSuggestedAutomations.ts
  frontend/src/tools/Automate.tsx
Labels: v2, size:L

#4286 Feature/v2/file manager UI improvements
  frontend/src/components/pageEditor/FileThumbnail.tsx
  frontend/src/components/pageEditor/PageEditor.module.css
  frontend/src/components/shared/TopControls.tsx
  frontend/src/hooks/useRainbowTheme.ts
  frontend/src/styles/theme.css
Labels: v2, size:XL

#4298 Fix invalid translation file in V2
  frontend/public/locales/en-GB/translation.json
Labels: v2, size:L

#4221 Redesgin ToolOperationConfig so types are known for single/multiple/custom tools
  frontend/src/hooks/tools/addPassword/useAddPasswordOperation.test.ts
  frontend/src/hooks/tools/addPassword/useAddPasswordOperation.ts
  frontend/src/hooks/tools/addWatermark/useAddWatermarkOperation.ts
  frontend/src/hooks/tools/automate/useAutomateOperation.ts
  frontend/src/hooks/tools/changePermissions/useChangePermissionsOperation.test.ts
  frontend/src/hooks/tools/changePermissions/useChangePermissionsOperation.ts
  frontend/src/hooks/tools/compress/useCompressOperation.ts
  frontend/src/hooks/tools/convert/useConvertOperation.ts
  frontend/src/hooks/tools/ocr/useOCROperation.ts
  frontend/src/hooks/tools/removeCertificateSign/useRemoveCertificateSignOperation.ts
  frontend/src/hooks/tools/removePassword/useRemovePasswordOperation.test.ts
  frontend/src/hooks/tools/removePassword/useRemovePasswordOperation.ts
  frontend/src/hooks/tools/repair/useRepairOperation.ts
  frontend/src/hooks/tools/sanitize/useSanitizeOperation.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/hooks/tools/singleLargePage/useSingleLargePageOperation.ts
  frontend/src/hooks/tools/split/useSplitOperation.ts
  frontend/src/hooks/tools/unlockPdfForms/useUnlockPdfFormsOperation.ts
  frontend/src/utils/automationExecutor.ts
Labels: v2, size:L

#4307 V2 Make FileId type opaque and use consistently throughout project
  frontend/src/components/fileEditor/FileEditor.tsx
  frontend/src/components/fileEditor/FileEditorThumbnail.tsx
  frontend/src/components/history/FileOperationHistory.tsx
  frontend/src/components/pageEditor/FileThumbnail.tsx
  frontend/src/components/pageEditor/PageEditor.tsx
  frontend/src/components/pageEditor/commands/pageCommands.ts
  frontend/src/components/pageEditor/hooks/usePageDocument.ts
  frontend/src/components/shared/FileGrid.tsx
  frontend/src/components/shared/FilePickerModal.tsx
  frontend/src/components/tools/convert/ConvertSettings.tsx
  frontend/src/components/viewer/Viewer.tsx
  frontend/src/contexts/FileContext.tsx
  frontend/src/contexts/FileManagerContext.tsx
  frontend/src/contexts/FilesModalContext.tsx
  frontend/src/contexts/IndexedDBContext.tsx
  frontend/src/contexts/file/FileReducer.ts
  frontend/src/contexts/file/fileActions.ts
  frontend/src/contexts/file/fileHooks.ts
  frontend/src/contexts/file/fileSelectors.ts
  frontend/src/contexts/file/lifecycle.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/hooks/useFileHandler.ts
  frontend/src/hooks/useFileManager.ts
  frontend/src/hooks/useThumbnailGeneration.ts
  frontend/src/hooks/useToolManagement.tsx
  frontend/src/services/fileProcessingService.ts
  frontend/src/services/fileStorage.ts
  frontend/src/services/thumbnailGenerationService.ts
  frontend/src/types/file.ts
  frontend/src/types/fileContext.ts
  frontend/src/types/pageEditor.ts
  frontend/src/utils/toolOperationTracker.ts
Labels: v2, size:XXL

#4313 V2 reduce tool boilerplate
  frontend/src/hooks/tools/shared/useBaseTool.ts
  frontend/src/tools/ChangePermissions.tsx
  frontend/src/tools/Compress.tsx
  frontend/src/tools/RemoveCertificateSign.tsx
  frontend/src/tools/RemovePassword.tsx
  frontend/src/tools/Repair.tsx
  frontend/src/tools/Sanitize.tsx
  frontend/src/tools/SingleLargePage.tsx
  frontend/src/tools/Split.tsx
  frontend/src/tools/UnlockPdfForms.tsx
Labels: v2, size:XL

#4323 Reduce required gap between files so more fit on the screen
  frontend/src/components/fileEditor/FileEditor.tsx
Labels: v2, size:XS
