Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-03, with the labels that each got.

#3086 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3088 chore: migrate vscode settings to editorconfig when possible
  .editorconfig
  .vscode/settings.json
Labels: size:L

#3084 Weasyprint forms #3077
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPDF.java
  src/main/java/stirling/software/SPDF/utils/FileToPdf.java
Labels: enhancement, Java, Back End, API, size:XS

#3095 Survey to allow booking meetings1
  build.gradle
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/js/pages/home.js
  src/main/resources/templates/home-legacy.html
  src/main/resources/templates/home.html
Labels: Front End, Translation, size:M

#3099 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:S

#3097 Devcontainer
  .devcontainer/devcontainer.json
  Dockerfile.dev
  scripts/init-setup.sh
Labels: Docker, size:L

#3102 Fix: Devcontainer permission
  .devcontainer/devcontainer.json
  Dockerfile.dev
  scripts/init-setup.sh
Labels: Docker, size:S

#3111 fix desktop client stuck at 90%
  src/main/java/stirling/software/SPDF/UI/impl/DesktopBrowser.java
Labels: Bug, Java, Front End, size:M

#3101 2926 bug undo feature of multitool delete your upload file
  src/main/resources/static/js/multitool/DragDropManager.js
  src/main/resources/static/js/multitool/PdfActionsManager.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/static/js/multitool/commands/add-page.js
  src/main/resources/static/js/multitool/commands/commands-sequence.js
  src/main/resources/static/js/multitool/commands/move-page.js
Labels: Bug, Front End, size:L

#3113 Fix highlighter
  src/main/resources/templates/view-pdf.html
Labels: Bug, Front End, size:S

#3114 Fix error banner not getting removed on correct upload
  src/main/resources/static/js/DecryptFiles.js
Labels: Bug, Front End, size:XS

#3121 Fix auto resizing images in view-pdf
  src/main/resources/templates/view-pdf.html
Labels: Bug, Front End, size:XS

#3116 translated newly added strings re business & user interaction
  src/main/resources/messages_sv_SE.properties
Labels: Translation, size:S

#3126 Update download-security-jar.sh downloadURL
  scripts/download-security-jar.sh
Labels: Docker, Security, size:S

#3127 Update messages_ja_JP.properties
  README.md
  src/main/resources/messages_ja_JP.properties
Labels: Documentation, Translation, size:M

#3129 Memory enhancements and PDF decompress API
  DeveloperGuide.md
  build.gradle
  exampleYmlFiles/docker-compose-latest-fat-security-postgres.yml
  exampleYmlFiles/docker-compose-latest-fat-security.yml
  exampleYmlFiles/docker-compose-latest-security-with-sso.yml
  exampleYmlFiles/docker-compose-latest-security.yml
  exampleYmlFiles/docker-compose-latest-ultra-lite-security.yml
  exampleYmlFiles/docker-compose-latest-ultra-lite.yml
  exampleYmlFiles/docker-compose-latest.yml
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/controller/api/AnalysisController.java
  src/main/java/stirling/software/SPDF/controller/api/CropController.java
  src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  src/main/java/stirling/software/SPDF/controller/api/MultiPageLayoutController.java
  src/main/java/stirling/software/SPDF/controller/api/RearrangePagesPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/ScalePagesController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySectionsController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySizeController.java
  src/main/java/stirling/software/SPDF/controller/api/ToSinglePageController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertImgPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToOffice.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ExtractCSVController.java
  src/main/java/stirling/software/SPDF/controller/api/filters/FilterController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoRenameController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoSplitPdfController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/BlankPageController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/DecompressPdfController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImageScansController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImagesController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/FlattenController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/MetadataController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/PageNumbersController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ShowJavascript.java
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  src/main/java/stirling/software/SPDF/controller/api/security/RedactController.java
  src/main/java/stirling/software/SPDF/controller/api/security/SanitizeController.java
  src/main/java/stirling/software/SPDF/model/PDFText.java
  src/main/java/stirling/software/SPDF/service/CustomPDDocumentFactory.java
  src/main/java/stirling/software/SPDF/utils/PdfUtils.java
Labels: Documentation, enhancement, Java, Back End, Docker, API, size:XL

#3075 Add zip
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/static/js/DecryptFiles.js
  src/main/resources/static/js/fileInput.js
  src/main/resources/templates/fragments/common.html
Labels: enhancement, Front End, Translation, size:M

#3151 issue #3137 completed
  src/main/resources/messages_es_ES.properties
Labels: Translation, size:M

#3147 Update VS Code extensions: Remove unnecessary Java tools and add new tools like EditorConfig, Docker and GitHub extensions.
  .vscode/extensions.json
  .vscode/settings.json
Labels: size:S

#3146 Update pre-commit hooks to latest versions
  .pre-commit-config.yaml
Labels: size:XS

#3141 Update and improve zh_TW Traditional Chinese locale
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:S

#3140 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:S

#3154 New Claim Attributes `mail` & `uid`
  src/main/java/stirling/software/SPDF/model/UsernameAttribute.java
Labels: enhancement, Java, size:XS

#3155 Fix: wrong credentials for Dockerfile.dev
  .github/labeler-config.yml
Labels: Github, size:XS

#3153 removal of all getByte loads
  .gitignore
  Dockerfile.fat
  build.gradle
  src/main/java/org/apache/pdfbox/examples/util/DeletingRandomAccessFile.java
  src/main/java/stirling/software/SPDF/controller/api/AnalysisController.java
  src/main/java/stirling/software/SPDF/controller/api/CropController.java
  src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  src/main/java/stirling/software/SPDF/controller/api/MultiPageLayoutController.java
  src/main/java/stirling/software/SPDF/controller/api/RearrangePagesPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/ScalePagesController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySectionsController.java
  src/main/java/stirling/software/SPDF/controller/api/ToSinglePageController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertImgPDFController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertPDFToOffice.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ExtractCSVController.java
  src/main/java/stirling/software/SPDF/controller/api/filters/FilterController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/AutoRenameController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/BlankPageController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/DecompressPdfController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImageScansController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImagesController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/FlattenController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/MetadataController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/PageNumbersController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/ShowJavascript.java
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  src/main/java/stirling/software/SPDF/model/api/PDFWithPageNums.java
  src/main/java/stirling/software/SPDF/service/CustomPDDocumentFactory.java
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
  testing/test.sh
  testing/test_webpages.sh
Labels: Java, Back End, API, size:L

#3156 Change Labeler configuration: Replace Dockerfile.* with Dockerfile.fat and Dockerfile.ultra-lite
  .github/labeler-config.yml
Labels: Github, size:XS

#3132 Add unit test for FileInfo.getFormattedFileSize
  src/main/java/stirling/software/SPDF/utils/FileInfo.java
  src/test/java/stirling/software/SPDF/utils/FileInfoTest.java
Labels: enhancement, Java, size:M

#3134 Update Catalan translations
  src/main/resources/messages_ca_CA.properties
Labels: Translation, size:L

#3161 Ukrainian translation has been improved
  src/main/resources/messages_uk_UA.properties
Labels: Translation, size:XL

#3108 Add: unoserver and more
  .devcontainer/devcontainer.json
  .devcontainer/git-init.sh
  .devcontainer/init-setup.sh
  Dockerfile.dev
  scripts/init-setup.sh
Labels: enhancement, size:L, Devtools

#3152 Implemented undo and redo mechanism for drawing signature
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/static/js/sign/signature-canvas.js
  src/main/resources/templates/sign.html
Labels: enhancement, Front End, Translation, size:M

#3166 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3168 Fix: string comparison and formatting inconsistencies in `CompressController`
  build.gradle
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
Labels: Java, Back End, API, size:S

#3170 Refactor test imports
  build.gradle
  src/test/java/stirling/software/SPDF/SPDFApplicationTest.java
  src/test/java/stirling/software/SPDF/config/security/CustomLogoutSuccessHandlerTest.java
  src/test/java/stirling/software/SPDF/config/security/database/DatabaseConfigTest.java
  src/test/java/stirling/software/SPDF/controller/api/RearrangePagesPDFControllerTest.java
  src/test/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPdfTest.java
  src/test/java/stirling/software/SPDF/utils/FileInfoTest.java
  src/test/java/stirling/software/SPDF/utils/FileToPdfTest.java
  src/test/java/stirling/software/SPDF/utils/GeneralUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/ImageProcessingUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/PdfUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/ProcessExecutorTest.java
  src/test/java/stirling/software/SPDF/utils/PropertyConfigsTest.java
  src/test/java/stirling/software/SPDF/utils/RequestUriUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/UrlUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/WebResponseUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/validation/ValidatorTest.java
Labels: size:L

#3175 Update springdoc plugin to 1.9.0 & Improve SwaggerHub Configuration and Gradle Setup
  .github/workflows/swagger.yml
  .gitignore
  build.gradle
Labels: API, Github, size:XS

#3177 Further compression fixes
  build.gradle
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/service/CustomPDFDocumentFactory.java
  src/main/resources/templates/fragments/common.html
  src/test/java/stirling/software/SPDF/controller/api/RotationControllerTest.java
Labels: Java, Front End, Back End, API, Test, size:XL

#3187 Fix Ukrainian translation
  src/main/resources/messages_uk_UA.properties
Labels: Translation, size:M

#3201 2385 feature request pdf multi tool to use new file input box
  src/main/resources/static/css/multi-tool.css
  src/main/resources/static/js/fileInput.js
  src/main/resources/static/js/multitool/PdfContainer.js
  src/main/resources/static/js/multitool/fileInput.js
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/multi-tool.html
Labels: enhancement, Front End, size:L

#3200 Add: German Translation
  src/main/resources/messages_de_DE.properties
Labels: enhancement, Translation, size:XS

#3198 Fix: Context Path Handling and Static Asset Loading Improvements
  src/main/java/stirling/software/SPDF/SPDFApplication.java
  src/main/java/stirling/software/SPDF/config/AppConfig.java
  src/main/resources/static/js/downloader.js
  src/main/resources/static/js/pages/home.js
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/home.html
  src/main/resources/templates/merge-pdfs.html
Labels: Java, Front End, Back End, size:M

#3192 Improve search UI and fix icon issues
  src/main/resources/static/css/theme/componentes.css
  src/main/resources/static/js/search.js
Labels: Bug, Front End, size:M

#3183 FR translation: undo/redo and survey.meeting.*
  src/main/resources/messages_fr_FR.properties
Labels: Translation, size:S

#3179 Normalize File Path for Font Resource Loading
  src/main/java/stirling/software/SPDF/controller/web/GeneralWebController.java
  src/main/java/stirling/software/SPDF/utils/GeneralUtils.java
Labels: enhancement, Java, Front End, Back End, size:S

#3202 Add default languages to OCR, fix compression for QPDF and embedded images
  Dockerfile
  Dockerfile.fat
  build.gradle
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/config/EndpointInspector.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineController.java
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineDirectoryProcessor.java
  src/main/java/stirling/software/SPDF/model/api/misc/OptimizePdfRequest.java
  src/main/java/stirling/software/SPDF/service/CustomPDFDocumentFactory.java
  src/main/java/stirling/software/SPDF/service/MetricsAggregatorService.java
  src/main/resources/static/js/fileInput.js
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/pipeline.html
  testing/test.sh
Labels: enhancement, Java, Front End, Back End, Docker, API, size:XXL

#3241 Security fixes, enterprise stuff and more
  Dockerfile
  Dockerfile.fat
  Dockerfile.ultra-lite
  build.gradle
  scripts/init-without-ocr.sh
  src/main/java/stirling/software/SPDF/EE/EEAppConfig.java
  src/main/java/stirling/software/SPDF/EE/KeygenLicenseVerifier.java
  src/main/java/stirling/software/SPDF/EE/LicenseKeyChecker.java
  src/main/java/stirling/software/SPDF/config/AppConfig.java
  src/main/java/stirling/software/SPDF/config/ConfigInitializer.java
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/config/EndpointInspector.java
  src/main/java/stirling/software/SPDF/config/EndpointInterceptor.java
  src/main/java/stirling/software/SPDF/config/EnterpriseEndpointFilter.java
  src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfBySizeController.java
  src/main/java/stirling/software/SPDF/controller/api/UserController.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPDF.java
  src/main/java/stirling/software/SPDF/controller/web/AccountWebController.java
  src/main/java/stirling/software/SPDF/controller/web/MetricsController.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/java/stirling/software/SPDF/service/CustomPDFDocumentFactory.java
  src/main/java/stirling/software/SPDF/service/PdfMetadataService.java
  src/main/java/stirling/software/SPDF/service/PostHogService.java
  src/main/java/stirling/software/SPDF/utils/RequestUriUtils.java
  src/main/resources/application.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/settings.yml.template
  src/main/resources/static/css/usage.css
  src/main/resources/static/js/usage.js
  src/main/resources/templates/account.html
  src/main/resources/templates/adminSettings.html
  src/main/resources/templates/usage.html
  src/test/java/stirling/software/SPDF/controller/api/converters/ConvertWebsiteToPdfTest.java
  testing/webpage_urls_full.txt
Labels: enhancement, Java, Front End, Back End, Docker, Translation, API, Test, size:XXL

#3237 Removed rounding causing images to scale on viewer
  src/main/resources/static/pdfjs-legacy/pdf.mjs
Labels: Bug, Front End, size:S

#3235 Fix missing translations 🇳🇴
  src/main/resources/messages_no_NB.properties
Labels: Translation, size:L

#3247 Python fix for new release
  Dockerfile
  Dockerfile.fat
  exampleYmlFiles/test_cicd.yml
  src/main/java/stirling/software/SPDF/controller/api/MergeController.java
Labels: Java, Back End, Docker, API, size:S

#3248 add chart js to 3rd party
  src/main/resources/static/js/thirdParty/chart.umd.min.js
  src/main/resources/templates/usage.html
Labels: enhancement, Front End, size:XS

#3251 Sanataize PDF improvements
  src/main/java/stirling/software/SPDF/controller/api/misc/MetadataController.java
  src/main/java/stirling/software/SPDF/controller/api/security/SanitizeController.java
  src/main/java/stirling/software/SPDF/model/api/security/SanitizePdfRequest.java
  src/main/java/stirling/software/SPDF/service/CustomPDFDocumentFactory.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/security/sanitize-pdf.html
Labels: Java, Front End, Back End, Translation, API, size:L

#3254 Change PDF load Get Info on PDF to readonly
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
Labels: Bug, Java, Back End, API, size:XS

#3256 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:M

#3259 🔧 Replace toList() with collect(Collectors.toList())
  src/main/java/stirling/software/SPDF/config/security/database/DatabaseService.java
Labels: Java, Back End, Security, size:XS

#3260 Update messages_pl_PL.properties
  src/main/resources/messages_pl_PL.properties
Labels: Translation, size:L

#3266 Add default authority assignment and enhanced user creation method
  src/main/java/stirling/software/SPDF/config/security/UserService.java
Labels: enhancement, Java, Back End, Security, size:S

#3271 Fix Ukrainian & Russian translation
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_uk_UA.properties
Labels: Translation, size:M
