Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-04, with the labels that each got.

#3281 Removing redundant logoutUrl from oauth
  src/main/java/stirling/software/SPDF/config/security/oauth2/OAuth2Configuration.java
  src/main/java/stirling/software/SPDF/controller/web/OtherWebController.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/java/stirling/software/SPDF/model/provider/GitHubProvider.java
  src/main/java/stirling/software/SPDF/model/provider/GoogleProvider.java
  src/main/java/stirling/software/SPDF/model/provider/KeycloakProvider.java
  src/main/java/stirling/software/SPDF/model/provider/Provider.java
Labels: Java, Front End, Back End, Security, size:S

#3196 Validation for input file
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/static/js/fileInput.js
  src/main/resources/templates/fragments/common.html
Labels: enhancement, Front End, Translation, size:S

#3287 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3253 2946 feature request integrate file selector with google drive and onedrive
  src/main/java/stirling/software/SPDF/EE/EEAppConfig.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/resources/settings.yml.template
  src/main/resources/static/css/fileSelect.css
  src/main/resources/static/images/google-drive.svg
  src/main/resources/static/js/fileInput.js
  src/main/resources/static/js/googleFilePicker.js
  src/main/resources/templates/fragments/common.html
Labels: enhancement, Java, Front End, Back End, size:L

#3296 fix: updated slovenian strings
  src/main/resources/messages_sl_SI.properties
Labels: Translation, size:M

#3294 Normalize settings.yml.template formatting to YAML 1.2 spec
  src/main/resources/settings.yml.template
Labels: Back End, size:S

#3292 Removed conflicting Oracle Java extension from devcontainer and VS Code config
  .devcontainer/devcontainer.json
  .vscode/extensions.json
Labels: size:XS, Devtools

#3291 Deprecate `EnterpriseEdition`
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
Labels: Java, size:XS

#3305 [bug] unoserver ip change to fix potention unoserver startup issues
  Dockerfile
  Dockerfile.fat
Labels: Bug, Docker, size:XS

#3302 Cookie banner
  src/main/resources/messages_en_GB.properties
  src/main/resources/static/css/cookieconsent.css
  src/main/resources/static/css/cookieconsentCustomisation.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/js/thirdParty/cookieconsent-config.js
  src/main/resources/static/js/thirdParty/cookieconsent.umd.js
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/fragments/footer.html
Labels: enhancement, Front End, Translation, size:L

#3299 Exclude Internal API User from Total User Count
  src/main/java/stirling/software/SPDF/config/security/UserService.java
Labels: enhancement, Java, Back End, Security, size:XS

#3282 Pipeline shows disabled endpoints fix (#2881)
  .github/workflows/build.yml
  exampleYmlFiles/docker-compose-latest-fat-endpoints-disabled.yml
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/config/EndpointInterceptor.java
  src/main/java/stirling/software/SPDF/controller/api/SettingsController.java
  src/main/resources/static/js/pipeline.js
  testing/allEndpointsRemovedSettings.yml
  testing/endpoints.txt
  testing/test.sh
  testing/test_disabledEndpoints.sh
Labels: Java, Front End, Back End, Docker, API, Github, size:XL

#3290 Fix: corrects the path to `version.properties`
  Dockerfile.fat
  build.gradle
Labels: Docker, size:XS

#3289 3164 bug issue on UI pdf multi tool
  src/main/resources/static/css/dragdrop.css
  src/main/resources/static/css/multi-tool.css
  src/main/resources/static/css/pdfActions.css
  src/main/resources/static/js/multitool/PdfActionsManager.js
Labels: Bug, Front End, size:L

#3308 Update build.gradle
  build.gradle
Labels: size:XS

#3313 fix: id for releases <a> tag in footer
  src/main/resources/templates/fragments/footer.html
Labels: Bug, Front End, size:XS

#3317 Manual Redaction: Text based redaction configured by default
  src/main/resources/static/css/redact.css
  src/main/resources/static/js/redact.js
  src/main/resources/templates/security/redact.html
Labels: enhancement, Front End, size:M

#3320 Added undefined check for posthog when analytics disabled
  src/main/resources/templates/fragments/common.html
Labels: Front End, size:XS

#3325 removed cdn import for cookieconsent library
  src/main/resources/static/js/thirdParty/cookieconsent-config.js
Labels: Front End, size:XS

#3326 Update PR-Demo-Comment.yml
  .github/workflows/PR-Demo-Comment-with-react.yml
Labels: Github, size:M

#3329 Update PR-Demo-Comment-with-react.yml
  .github/workflows/PR-Demo-Comment-with-react.yml
Labels: Github, size:XS

#3327 Removed empty spaces shown when language suppression used
  build.gradle
  src/main/resources/static/css/navbar.css
  src/main/resources/templates/fragments/languageEntry.html
Labels: Front End, size:M

#3333 MacOS `x86_64` installer fix 🙏🏾
  .github/workflows/multiOSReleases.yml
  build.gradle
Labels: Github, size:S

#3338 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3337 Complete zh_TW Traditional Chinese translation
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:L

#3345 Change PR deploy to use security (Enable '/deploypr security' command)
  .github/workflows/PR-Demo-Comment-with-react.yml
Labels: Github, size:M

#3334 Upload File Size Limit
  src/main/java/stirling/software/SPDF/config/AppConfig.java
  src/main/java/stirling/software/SPDF/controller/web/GlobalUploadLimitWebController.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/settings.yml.template
  src/main/resources/static/js/downloader.js
  src/main/resources/static/js/fileInput.js
  src/main/resources/templates/fragments/common.html
Labels: enhancement, Java, Front End, Back End, Translation, size:L

#3346 Allow non cert files to be enterprise
  build.gradle
  src/main/java/stirling/software/SPDF/EE/KeygenLicenseVerifier.java
Labels: Java, size:M

#3348 3335 feature request add app version to posthog
  src/main/java/stirling/software/SPDF/service/PostHogService.java
  src/main/resources/templates/fragments/common.html
Labels: enhancement, Java, Front End, size:XS

#3350 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3358 fix pipelines via changing to service
  build.gradle
  src/main/java/stirling/software/SPDF/config/AppConfig.java
  src/main/java/stirling/software/SPDF/controller/web/GlobalUploadLimitWebController.java
  src/main/java/stirling/software/SPDF/controller/web/UploadLimitService.java
  src/main/resources/templates/fragments/common.html
Labels: Java, Front End, Back End, size:L

#3356 Update messages_pt_BR.properties
  src/main/resources/messages_pt_BR.properties
Labels: Translation, size:M

#3362 Update and improve zh_TW Traditional Chinese locale
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:M

#3363 Update messages_tr_TR.properties
  src/main/resources/messages_tr_TR.properties
Labels: Translation, size:XL

#3360 2728 bug signed rotated document different than preview
  src/main/resources/static/js/draggable-utils.js
  src/main/resources/static/js/fileInput.js
Labels: Front End, size:M

#3365 Update messages_fr_FR.properties to fix translation mistake
  src/main/resources/messages_fr_FR.properties
Labels: Translation, size:XS

#3373 fix security deploy
  .github/workflows/PR-Demo-Comment-with-react.yml
Labels: Github, size:XS

#3376 Bump ruff to v0.11.6 and gitleaks to v8.24.3 in pre-commit config
  .pre-commit-config.yaml
Labels: size:XS

#3375 Update Google Java Format to v1.26.0 across devcontainer, VSCode, and Gradle configuration
  .devcontainer/devcontainer.json
  .vscode/settings.json
  build.gradle
Labels: size:XS, Devtools

#3378 Add SHOW_SURVEY Environment variable to Docker
  DeveloperGuide.md
  exampleYmlFiles/docker-compose-latest-fat-endpoints-disabled.yml
  exampleYmlFiles/docker-compose-latest-fat-security-postgres.yml
  exampleYmlFiles/docker-compose-latest-fat-security.yml
  exampleYmlFiles/docker-compose-latest-security-with-sso.yml
  exampleYmlFiles/docker-compose-latest-security.yml
  exampleYmlFiles/docker-compose-latest-ultra-lite-security.yml
  exampleYmlFiles/docker-compose-latest-ultra-lite.yml
  exampleYmlFiles/docker-compose-latest.yml
  src/main/java/stirling/software/SPDF/controller/web/HomeWebController.java
  src/main/resources/static/js/pages/home.js
  src/main/resources/templates/home.html
Labels: Documentation, enhancement, Java, Front End, Back End, Docker, size:S

#3383 Support domain `User` instances in `getCurrentUsername` method
  src/main/java/stirling/software/SPDF/config/security/UserService.java
Labels: enhancement, Java, Back End, Security, size:XS

#3398 Changed footer to be more responsive to page size
  src/main/resources/static/css/footer.css
  src/main/resources/templates/fragments/footer.html
Labels: enhancement, Front End, size:S

#3400 Changes from Version 2.2.0 to 2.8.6 `org.springdoc:springdoc-openapi-starter-webmvc-ui`
  build.gradle
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineController.java
  src/main/java/stirling/software/SPDF/controller/api/security/ValidateSignatureController.java
  src/main/java/stirling/software/SPDF/model/api/PDFFile.java
  src/main/resources/application.properties
Labels: Java, Back End, API, size:S

#3405 Update messages_es_ES.properties
  src/main/resources/messages_es_ES.properties
Labels: Translation, size:L

#3416 Update German properties
  scripts/ignore_translation.toml
  src/main/resources/messages_de_DE.properties
Labels: Documentation, Translation, size:L

#3425 Upgrade Gradle to 8.14 in CI Workflows and Gradle Wrapper
  .github/workflows/multiOSReleases.yml
  .github/workflows/push-docker.yml
  .github/workflows/releaseArtifacts.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  testing/test_webpages.sh
Labels: Docker, Github, size:M

#3423 Remove read only from forms
  src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  src/main/java/stirling/software/SPDF/controller/api/misc/UnlockPDFFormsController.java
  src/main/java/stirling/software/SPDF/controller/web/OtherWebController.java
  src/main/java/stirling/software/SPDF/controller/web/UploadLimitService.java
  src/main/resources/messages_ar_AR.properties
  src/main/resources/messages_az_AZ.properties
  src/main/resources/messages_bg_BG.properties
  src/main/resources/messages_ca_CA.properties
  src/main/resources/messages_cs_CZ.properties
  src/main/resources/messages_da_DK.properties
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_el_GR.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/messages_en_US.properties
  src/main/resources/messages_es_ES.properties
  src/main/resources/messages_eu_ES.properties
  src/main/resources/messages_fa_IR.properties
  src/main/resources/messages_fr_FR.properties
  src/main/resources/messages_ga_IE.properties
  src/main/resources/messages_hi_IN.properties
  src/main/resources/messages_hr_HR.properties
  src/main/resources/messages_hu_HU.properties
  src/main/resources/messages_id_ID.properties
  src/main/resources/messages_it_IT.properties
  src/main/resources/messages_ja_JP.properties
  src/main/resources/messages_ko_KR.properties
  src/main/resources/messages_nl_NL.properties
  src/main/resources/messages_no_NB.properties
  src/main/resources/messages_pl_PL.properties
  src/main/resources/messages_pt_BR.properties
  src/main/resources/messages_pt_PT.properties
  src/main/resources/messages_ro_RO.properties
  src/main/resources/messages_ru_RU.properties
  src/main/resources/messages_sk_SK.properties
  src/main/resources/messages_sl_SI.properties
  src/main/resources/messages_sr_LATN_RS.properties
  src/main/resources/messages_sv_SE.properties
  src/main/resources/messages_th_TH.properties
  src/main/resources/messages_tr_TR.properties
  src/main/resources/messages_uk_UA.properties
  src/main/resources/messages_vi_VN.properties
  src/main/resources/messages_zh_BO.properties
  src/main/resources/messages_zh_CN.properties
  src/main/resources/messages_zh_TW.properties
  src/main/resources/templates/fragments/navElements.html
  src/main/resources/templates/home-legacy.html
  src/main/resources/templates/misc/unlock-pdf-forms.html
Labels: enhancement, Java, Front End, Back End, Translation, API, size:L

#3445 Version bump
  build.gradle
Labels: size:XS

#3448 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:S

#3449 Validate H2 datasource configuration in DatabaseService
  src/main/java/stirling/software/SPDF/config/security/database/DatabaseService.java
Labels: Java, Back End, Security, size:S

#3450 Internationalize logout message
  src/main/java/stirling/software/SPDF/controller/web/AccountWebController.java
  src/main/resources/messages_de_DE.properties
  src/main/resources/messages_en_GB.properties
  src/main/resources/templates/login.html
Labels: Java, Front End, Back End, Translation, size:XS

#3451 Added missing Hungarian translations.
  src/main/resources/messages_hu_HU.properties
Labels: Translation, size:L
