Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-05, with the labels that each got.

#3458 Validate H2 Database Type and URL Consistency for Custom Databases
  src/main/java/stirling/software/SPDF/config/security/database/DatabaseService.java
Labels: Java, Back End, Security, size:M

#3456 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3464 Update language list to use native names
  src/main/resources/templates/fragments/languages.html
Labels: Front End, Translation, size:S

#3469 Fix NullPointerException by Enabling Constructor Injection for Color Replacement Components
  src/main/java/stirling/software/SPDF/controller/api/misc/ReplaceAndInvertColorController.java
  src/main/java/stirling/software/SPDF/service/misc/ReplaceAndInvertColorService.java
Labels: Bug, Java, Back End, API, size:XS

#3455 Add Email Sending Service with Attachment Support
  .github/labeler-config.yml
  build.gradle
  src/main/java/stirling/software/SPDF/config/security/mail/EmailService.java
  src/main/java/stirling/software/SPDF/config/security/mail/MailConfig.java
  src/main/java/stirling/software/SPDF/controller/api/EmailController.java
  src/main/java/stirling/software/SPDF/model/ApplicationProperties.java
  src/main/java/stirling/software/SPDF/model/api/Email.java
  src/main/resources/settings.yml.template
  src/test/java/stirling/software/SPDF/config/security/mail/EmailServiceTest.java
  src/test/java/stirling/software/SPDF/controller/api/EmailControllerTest.java
Labels: enhancement, Java, Back End, Security, API, Test, Github, size:L

#3490 Auto scale
  src/main/resources/static/css/general.css
  src/main/resources/static/css/navbar.css
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/home.html
Labels: Front End, size:M

#3499 Potential fix for code scanning alert no. 224: DOM text reinterpreted as HTML
  src/main/resources/static/js/tab-container.js
Labels: Bug, Front End, size:XS

#3502 pixel changes, redact color fix, version bump, aggressive compression
  build.gradle
  src/main/java/stirling/software/SPDF/EE/EEAppConfig.java
  src/main/java/stirling/software/SPDF/config/AppConfig.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/controller/api/security/RedactController.java
  src/main/java/stirling/software/SPDF/model/api/security/RedactPdfRequest.java
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/home.html
Labels: Java, Front End, Back End, API, size:L

#3457 Refactor permission variable names
  src/main/java/stirling/software/SPDF/controller/api/AnalysisController.java
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  src/main/java/stirling/software/SPDF/controller/api/security/PasswordController.java
  src/main/java/stirling/software/SPDF/model/api/security/AddPasswordRequest.java
  src/main/resources/templates/security/add-password.html
  src/main/resources/templates/security/change-permissions.html
Labels: Java, Front End, Back End, API, size:L

#2981 Fix French translation.
  src/main/resources/messages_fr_FR.properties
Labels: Translation, size:S

#3497 Potential fix for code scanning alert no. 11: DOM text reinterpreted as HTML
  src/main/resources/static/js/pipeline.js
Labels: Bug, Front End, size:M

#3505 accept/decline cookies based on analytics and hide cookie banner when…
  src/main/resources/static/js/pages/home.js
Labels: Front End, size:S

#3506 added Malayalam language
  src/main/resources/messages_ml_ML.properties
  src/main/resources/templates/fragments/languages.html
Labels: Front End, Translation, size:M

#3509 Fix README enterprise link
  README.md
Labels: Documentation, size:XS

#3511 Use Thymeleaf `th:src` for `redact.js` to ensure correct resource path resolution
  src/main/resources/templates/security/redact.html
Labels: Bug, Front End, size:XS

#3510 updated the languages list
  README.md
Labels: Documentation, size:XS

#3515 Standardize Quoted Path Syntax in Thymeleaf `th:href` for Consistent Link Resolution
  DeveloperGuide.md
  src/main/resources/templates/adminSettings.html
Labels: Documentation, Front End, size:XS

#3522 Update legal URLs and improve OpenAPI metadata configuration
  src/main/java/stirling/software/SPDF/config/InitialSetup.java
  src/main/java/stirling/software/SPDF/config/MetricsConfig.java
  src/main/java/stirling/software/SPDF/config/OpenApiConfig.java
  src/main/resources/settings.yml.template
  testing/allEndpointsRemovedSettings.yml
Labels: Java, Back End, API, size:M

#3524 Update zh_TW Traditional Chinese locale
  src/main/resources/messages_zh_TW.properties
Labels: Translation, size:S

#3527 Update messages_es_ES.properties
  src/main/resources/messages_es_ES.properties
Labels: Translation, size:S

#3535 Floating keys for pro users
  build.gradle
  src/main/java/stirling/software/SPDF/EE/KeygenLicenseVerifier.java
Labels: Java, size:L

#3537 JUnits JUnits JUnits, so many JUnits
  build.gradle
  src/main/java/stirling/software/SPDF/EE/EEAppConfig.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertMarkdownToPdf.java
  src/main/java/stirling/software/SPDF/controller/api/misc/CompressController.java
  src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  src/main/java/stirling/software/SPDF/controller/api/security/GetInfoOnPDF.java
  src/main/java/stirling/software/SPDF/service/LanguageService.java
  src/test/java/stirling/software/SPDF/config/security/mail/EmailServiceTest.java
  src/test/java/stirling/software/SPDF/controller/api/EmailControllerTest.java
  src/test/java/stirling/software/SPDF/service/CertificateValidationServiceTest.java
  src/test/java/stirling/software/SPDF/service/CustomPDFDocumentFactoryTest.java
  src/test/java/stirling/software/SPDF/service/LanguageServiceBasicTest.java
  src/test/java/stirling/software/SPDF/service/LanguageServiceTest.java
  src/test/java/stirling/software/SPDF/service/PdfImageRemovalServiceTest.java
  src/test/java/stirling/software/SPDF/service/PdfMetadataServiceBasicTest.java
  src/test/java/stirling/software/SPDF/service/PdfMetadataServiceTest.java
  src/test/java/stirling/software/SPDF/service/SignatureServiceTest.java
  src/test/java/stirling/software/SPDF/service/SpyPDFDocumentFactory.java
  src/test/java/stirling/software/SPDF/utils/CheckProgramInstallTest.java
  src/test/java/stirling/software/SPDF/utils/CustomHtmlSanitizerTest.java
  src/test/java/stirling/software/SPDF/utils/FileMonitorTest.java
  src/test/java/stirling/software/SPDF/utils/FileToPdfTest.java
  src/test/java/stirling/software/SPDF/utils/PDFToFileTest.java
  src/test/java/stirling/software/SPDF/utils/ProcessExecutorTest.java
  src/test/java/stirling/software/SPDF/utils/RequestUriUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/UIScalingTest.java
  src/test/java/stirling/software/SPDF/utils/UrlUtilsTest.java
  src/test/java/stirling/software/SPDF/utils/misc/CustomColorReplaceStrategyTest.java
  src/test/java/stirling/software/SPDF/utils/misc/HighContrastColorReplaceDeciderTest.java
  src/test/java/stirling/software/SPDF/utils/misc/InvertFullColorStrategyTest.java
  src/test/java/stirling/software/SPDF/utils/misc/PdfTextStripperCustomTest.java
  src/test/java/stirling/software/SPDF/utils/misc/ReplaceAndInvertColorStrategyTest.java
  src/test/java/stirling/software/SPDF/utils/propertyeditor/StringToArrayListPropertyEditorTest.java
  src/test/java/stirling/software/SPDF/utils/propertyeditor/StringToMapPropertyEditorTest.java
  src/test/resources/example.pdf
Labels: Java, Back End, API, Test, size:XXL

#3554 Fix test compilation around pipeline processor
  src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessor.java
  src/test/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessorTest.java
Labels: Java, Back End, API, Test, size:M, codex

#3555 Fix TemplateResolver and LibreOfficeListener bugs
  src/main/java/stirling/software/SPDF/LibreOfficeListener.java
  src/main/java/stirling/software/SPDF/config/FileFallbackTemplateResolver.java
  src/main/java/stirling/software/SPDF/model/InputStreamTemplateResource.java
Labels: Bug, Java, Back End, size:S, codex

#3557 Add additional unit tests for utils and EE
  src/test/java/stirling/software/SPDF/EE/LicenseKeyCheckerTest.java
  src/test/java/stirling/software/SPDF/utils/GeneralUtilsAdditionalTest.java
  src/test/java/stirling/software/SPDF/utils/PdfUtilsTest.java
Labels: Test, size:L, codex

#3518 remove legacy homepage
  src/main/java/stirling/software/SPDF/controller/web/HomeWebController.java
  src/main/resources/static/css/home-legacy.css
  src/main/resources/static/js/favourites.js
  src/main/resources/static/js/homecard-legacy.js
  src/main/resources/static/js/pages/home.js
  src/main/resources/templates/fragments/featureGroupHeaderLegacy.html
  src/main/resources/templates/home-legacy.html
  src/main/resources/templates/home.html
Labels: Java, Front End, Back End, size:XXL

#3560 Update home.html
  src/main/resources/templates/home.html
Labels: Front End, size:XS

#3567 Ukrainian translation
  src/main/resources/messages_uk_UA.properties
Labels: Translation, size:L

#3561 Enhance email error handling and expand test coverage
  src/main/java/stirling/software/SPDF/config/security/mail/EmailService.java
  src/main/java/stirling/software/SPDF/controller/api/EmailController.java
  src/test/java/stirling/software/SPDF/config/security/mail/EmailServiceTest.java
  src/test/java/stirling/software/SPDF/config/security/mail/MailConfigTest.java
  src/test/java/stirling/software/SPDF/controller/api/EmailControllerTest.java
Labels: enhancement, Java, Back End, Security, API, Test, size:L

#3572 Russian translation
  src/main/resources/messages_ru_RU.properties
Labels: Translation, size:L

#3575 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:S

#3574 Fix Chinese localization split page numbering
  src/main/resources/messages_zh_CN.properties
Labels: Bug, Translation, size:XS

#3582 Standardize GitHub App Bot Authentication Across Workflows
  .github/actions/setup-bot/action.yml
  .github/workflows/check_properties.yml
  .github/workflows/licenses-update.yml
  .github/workflows/pre_commit.yml
  .github/workflows/sync_files.yml
Labels: Test, Github, size:L

#3583 Replace `any()` with `anyList()` in Mockito tests for stronger type safety
  common/src/test/java/stirling/software/common/util/CheckProgramInstallTest.java
  common/src/test/java/stirling/software/common/util/PDFToFileTest.java
Labels: enhancement, size:M

#3587 security fixes
  Dockerfile
  Dockerfile.dev
  Dockerfile.fat
  build.gradle
Labels: Docker, size:XS, Devtools

#3605 Include `common` in Spotless formatting
  .vscode/settings.json
  build.gradle
  common/src/main/java/stirling/software/common/configuration/AppConfig.java
  common/src/main/java/stirling/software/common/configuration/FileFallbackTemplateResolver.java
  common/src/main/java/stirling/software/common/configuration/InstallationPathConfig.java
  common/src/main/java/stirling/software/common/configuration/YamlPropertySourceFactory.java
  common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  common/src/main/java/stirling/software/common/model/api/converters/HTMLToPdfRequest.java
  common/src/main/java/stirling/software/common/model/oauth2/GitHubProvider.java
  common/src/main/java/stirling/software/common/model/oauth2/GoogleProvider.java
  common/src/main/java/stirling/software/common/model/oauth2/KeycloakProvider.java
  common/src/main/java/stirling/software/common/model/oauth2/Provider.java
  common/src/main/java/stirling/software/common/util/FileMonitor.java
  common/src/main/java/stirling/software/common/util/PdfUtils.java
  common/src/main/java/stirling/software/common/util/ProviderUtils.java
  common/src/main/java/stirling/software/common/util/misc/CustomColorReplaceStrategy.java
  common/src/main/java/stirling/software/common/util/misc/InvertFullColorStrategy.java
  common/src/main/java/stirling/software/common/util/propertyeditor/StringToArrayListPropertyEditor.java
  common/src/main/java/stirling/software/common/util/propertyeditor/StringToMapPropertyEditor.java
  common/src/test/java/stirling/software/common/util/FileMonitorTest.java
  common/src/test/java/stirling/software/common/util/ProviderUtilsTest.java
  common/src/test/java/stirling/software/common/util/RequestUriUtilsTest.java
  common/src/test/java/stirling/software/common/util/misc/HighContrastColorReplaceDeciderTest.java
  common/src/test/java/stirling/software/common/util/misc/InvertFullColorStrategyTest.java
  common/src/test/java/stirling/software/common/util/misc/ReplaceAndInvertColorStrategyTest.java
  common/src/test/java/stirling/software/common/util/propertyeditor/StringToArrayListPropertyEditorTest.java
Labels: size:L

#3612 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:XS

#3615 Use setup-bot token for GitHub Actions and fix GH_APP_ID secret reference
  .github/workflows/check_properties.yml
  .github/workflows/sync_files.yml
Labels: Github, size:XS

#3614 Fix Tibetan locale code to bo_CN and update translation ignore configurations
  README.md
  scripts/counter_translation.py
  scripts/ignore_translation.toml
  src/main/resources/messages_bo_CN.properties
  src/main/resources/templates/fragments/languages.html
Labels: Documentation, Front End, Translation, size:XL

#3530 Added scan filter feature
  src/main/java/stirling/software/SPDF/controller/api/misc/FakeScanController.java
  src/main/java/stirling/software/SPDF/controller/api/misc/FakeScanControllerWIP.java
  src/main/java/stirling/software/SPDF/model/api/misc/FakeScanRequest.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/templates/fragments/navElements.html
  src/main/resources/templates/misc/fake-scan.html
Labels: enhancement, Java, Front End, Back End, Translation, API, size:XXL
