Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-10, with the labels that each got.

#4572 Add translations for ar-AR, de-DE, fr-FR, it-IT, pt-BR, ru-RU and ena…
  frontend/public/locales/ar-AR/translation.json
  frontend/public/locales/es-ES/translation.json
  frontend/public/locales/fr-FR/translation.json
  frontend/public/locales/ja-JP/translation.json
  frontend/public/locales/pt-BR/translation.json
  frontend/public/locales/ru-RU/translation.json
  frontend/src/components/shared/LanguageSelector.tsx
  scripts/translations/README.md
  scripts/translations/json_validator.py
  scripts/translations/validate_json_structure.py
  scripts/translations/validate_placeholders.py
Labels: Documentation, v2, size:XXL

#4530 shortcuts and config menu
  frontend/public/locales/en-GB/translation.json
  frontend/src/App.tsx
  frontend/src/components/hotkeys/HotkeyDisplay.tsx
  frontend/src/components/shared/AppConfigModal.css
  frontend/src/components/shared/AppConfigModal.tsx
  frontend/src/components/shared/QuickAccessBar.tsx
  frontend/src/components/shared/config/configNavSections.tsx
  frontend/src/components/shared/config/configSections/HotkeysSection.tsx
  frontend/src/components/shared/config/configSections/Overview.tsx
  frontend/src/components/shared/config/types.ts
  frontend/src/components/tools/toolPicker/ToolButton.tsx
  frontend/src/contexts/HotkeyContext.tsx
  frontend/src/contexts/ToolWorkflowContext.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/styles/theme.css
  frontend/src/utils/hotkeys.ts
Labels: v2, size:XXL

#4574 Fix/v2/automate_settings_gap_fill
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/tools/addAttachments/AddAttachmentsSettings.tsx
  frontend/src/components/tools/addPageNumbers/AddPageNumbersAppearanceSettings.tsx
  frontend/src/components/tools/addPageNumbers/AddPageNumbersAutomationSettings.tsx
  frontend/src/components/tools/addPageNumbers/AddPageNumbersPositionSettings.tsx
  frontend/src/components/tools/addStamp/AddStampAutomationSettings.tsx
  frontend/src/components/tools/addStamp/StampPositionFormattingSettings.tsx
  frontend/src/components/tools/addStamp/StampSetupSettings.tsx
  frontend/src/components/tools/automate/ToolConfigurationModal.tsx
  frontend/src/components/tools/automate/ToolList.tsx
  frontend/src/components/tools/automate/ToolSelector.tsx
  frontend/src/components/tools/certSign/CertSignAutomationSettings.tsx
  frontend/src/components/tools/crop/CropAutomationSettings.tsx
  frontend/src/components/tools/crop/CropCoordinateInputs.tsx
  frontend/src/components/tools/crop/CropSettings.tsx
  frontend/src/components/tools/removePages/RemovePagesSettings.tsx
  frontend/src/components/tools/rotate/RotateAutomationSettings.tsx
  frontend/src/components/tools/split/SplitAutomationSettings.tsx
  frontend/src/data/toolsTaxonomy.ts
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/automate/useAutomationForm.ts
  frontend/src/hooks/tools/automate/useSuggestedAutomations.ts
  frontend/src/hooks/useToolNavigation.ts
  frontend/src/tools/AddAttachments.tsx
  frontend/src/tools/AddPageNumbers.tsx
  frontend/src/tools/AddStamp.tsx
  frontend/src/utils/automationExecutor.ts
  frontend/src/utils/urlRouting.ts
Labels: v2, size:XXL

#4579 ph-no-capture tags
  frontend/src/components/fileEditor/FileEditorThumbnail.tsx
  frontend/src/components/fileManager/FileInfoCard.tsx
  frontend/src/components/fileManager/FileListItem.tsx
  frontend/src/components/pageEditor/FileThumbnail.tsx
  frontend/src/components/pageEditor/PageThumbnail.tsx
  frontend/src/components/shared/filePreview/DocumentThumbnail.tsx
  frontend/src/components/tools/addPageNumbers/PageNumberPreview.tsx
  frontend/src/components/tools/shared/ResultsPreview.tsx
  frontend/src/components/viewer/LocalEmbedPDF.tsx
  frontend/src/components/viewer/ThumbnailSidebar.tsx
Labels: v2, size:M

#4580 Created shared component
  frontend/src/components/shared/ToolIcon.tsx
  frontend/src/components/tools/automate/AutomationEntry.tsx
  frontend/src/components/tools/shared/SuggestedToolsSection.tsx
  frontend/src/components/tools/toolPicker/ToolButton.tsx
  frontend/src/styles/theme.css
Labels: enhancement, v2, size:L

#4544 Feature/adjust colors contrast tool
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en-US/translation.json
  frontend/src/components/shared/sliderWithInput/SliderWithInput.tsx
  frontend/src/components/tools/adjustContrast/AdjustContrastBasicSettings.tsx
  frontend/src/components/tools/adjustContrast/AdjustContrastColorSettings.tsx
  frontend/src/components/tools/adjustContrast/AdjustContrastPreview.tsx
  frontend/src/components/tools/adjustContrast/AdjustContrastSingleStepSettings.tsx
  frontend/src/components/tools/adjustContrast/utils.ts
  frontend/src/components/tools/shared/createToolFlow.tsx
  frontend/src/data/useTranslatedToolRegistry.tsx
  frontend/src/hooks/tools/adjustContrast/useAdjustContrastOperation.ts
  frontend/src/hooks/tools/adjustContrast/useAdjustContrastParameters.ts
  frontend/src/tools/AdjustContrast.tsx
Labels: v2, size:XL

#4585 Config becomes account when enableLogin
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/shared/QuickAccessBar.tsx
Labels: v2, size:XS

#4586 Feature/v2/navigate save prompt
  frontend/src/components/pageEditor/PageEditor.tsx
  frontend/src/components/pageEditor/PageThumbnail.tsx
  frontend/src/components/pageEditor/commands/pageCommands.ts
  frontend/src/components/shared/NavigationWarningModal.tsx
  frontend/src/components/viewer/EmbedPdfViewer.tsx
  frontend/src/components/viewer/SignatureAPIBridge.tsx
  frontend/src/contexts/NavigationContext.tsx
  frontend/src/contexts/file/fileActions.ts
  frontend/src/services/documentManipulationService.ts
  frontend/src/services/enhancedPDFProcessingService.ts
  frontend/src/services/fileStubHelpers.ts
  frontend/src/services/pdfExportHelpers.ts
  frontend/src/services/pdfExportService.ts
  frontend/src/services/thumbnailGenerationService.ts
  frontend/src/utils/thumbnailUtils.ts
Labels: v2, size:XL

#4582 Bug/v2/mime
  frontend/src/components/fileEditor/AddFileCard.tsx
  frontend/src/components/shared/FileUploadButton.tsx
  frontend/src/components/shared/LandingPage.tsx
Labels: size:XS, Bugfix

#4461 feat(merge): use metadata for sortByDate
  app/core/src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  app/core/src/main/resources/static/js/merge.js
  app/core/src/main/resources/templates/merge-pdfs.html
Labels: enhancement, Java, Front End, Back End, API, size:L

#4565 fix(scanner-effect): lower default DPI in ScannerEffectRequest
  app/core/src/main/java/stirling/software/SPDF/model/api/misc/ScannerEffectRequest.java
Labels: Java, API, size:XS, Bugfix

#4598 fix(ci): 🛡️ mitigate CVE-2025-8869 by enforcing wheels-only pip installs and upgrading pinned dependencies
  .github/scripts/requirements_dev.txt
  .github/scripts/requirements_pre_commit.txt
  .github/scripts/requirements_sync_readme.txt
  .github/workflows/pre_commit.yml
  .github/workflows/sync_files.yml
  testing/cucumber/requirements.txt
Labels: Test, Github, size:L, Devtools, Bugfix, ci

#4577 🌐 Update messages_ru_RU.properties
  app/core/src/main/resources/messages_ru_RU.properties
Labels: Translation, size:M

#4588 fix(viewer): make initial zoom setup robust and clear timers in `ZoomAPIBridge`
  frontend/src/components/viewer/ZoomAPIBridge.tsx
Labels: v2, size:M, Bugfix

#4584 Feature/v2/toggle_for_auto_unzip
  frontend/public/locales/en-GB/translation.json
  frontend/src/App.tsx
  frontend/src/components/fileEditor/FileEditor.tsx
  frontend/src/components/fileEditor/FileEditorThumbnail.tsx
  frontend/src/components/fileManager/FileListItem.tsx
  frontend/src/components/shared/config/configNavSections.tsx
  frontend/src/components/shared/config/configSections/GeneralSection.tsx
  frontend/src/contexts/FileManagerContext.tsx
  frontend/src/contexts/PreferencesContext.tsx
  frontend/src/hooks/tools/scannerImageSplit/useScannerImageSplitOperation.ts
  frontend/src/hooks/tools/shared/useToolOperation.ts
  frontend/src/hooks/tools/shared/useToolResources.ts
  frontend/src/services/indexedDBManager.ts
  frontend/src/services/preferencesService.ts
  frontend/src/services/zipFileService.ts
  frontend/src/tests/convert/ConvertIntegration.test.tsx
  frontend/src/tests/convert/ConvertSmartDetectionIntegration.test.tsx
Labels: v2, size:XL

#4619 V2 File Editor Shortcuts
  frontend/public/locales/en-GB/translation.json
  frontend/src/components/fileEditor/FileEditor.module.css
  frontend/src/components/fileEditor/FileEditor.tsx
  frontend/src/components/fileEditor/FileEditorThumbnail.tsx
Labels: enhancement, v2, size:L
