Repository Stirling-Tools/Stirling-PDF, pull requests merged in 2025-06, with the labels that each got.

#3634 Update messages_it_IT.properties
  src/main/resources/messages_it_IT.properties
Labels: Translation, size:M

#3637 Update build.yml
  .github/workflows/build.yml
Labels: Docker, Github, size:XS

#3618 Update messages_de_DE.properties
  src/main/resources/messages_de_DE.properties
Labels: Translation, size:L

#3621 Fix error display for Split by Chapter
  src/main/java/stirling/software/SPDF/controller/api/SplitPdfByChaptersController.java
Labels: Bug, Java, Back End, API, size:XS, codex

#3651 bootRun to work at root
  build.gradle
  stirling-pdf/build.gradle
Labels: size:XS

#3650 Add EML to PDF conversion functionality
  common/build.gradle
  common/src/main/java/stirling/software/common/model/api/converters/EmlToPdfRequest.java
  common/src/main/java/stirling/software/common/util/EmlToPdf.java
  src/main/java/stirling/software/SPDF/controller/api/converters/ConvertEmlToPDF.java
  src/main/java/stirling/software/SPDF/controller/web/ConverterWebController.java
  src/main/resources/messages_en_GB.properties
  src/main/resources/templates/convert/eml-to-pdf.html
  src/main/resources/templates/fragments/navElements.html
Labels: enhancement, Java, Front End, Back End, Translation, API, size:XXL

#3661 Disabled auto capture for posthog
  src/main/resources/templates/fragments/common.html
Labels: Front End, size:XS

#3678 updating path in script
  scripts/counter_translation.py
Labels: Documentation, size:XS

#3684 Update check_language_properties.py
  .github/scripts/check_language_properties.py
Labels: Github, size:XS

#3676 Update messages_pt_BR.properties
  stirling-pdf/src/main/resources/messages_pt_BR.properties
Labels: Translation, size:M

#3699 chore: Improve VSCode Java Project Configuration with Explicit Source Paths
  .vscode/settings.json
Labels: size:XS, Devtools

#3698 Fix: Assign Internal API User to Internal Team and Eager-Load User’s Team Association
  proprietary/src/main/java/stirling/software/proprietary/security/InitialSecuritySetup.java
  proprietary/src/main/java/stirling/software/proprietary/security/model/User.java
  proprietary/src/main/java/stirling/software/proprietary/security/service/UserService.java
  stirling-pdf/src/main/resources/static/js/pages/edit-table-of-contents.js
  stirling-pdf/src/test/java/stirling/software/SPDF/controller/api/MergeControllerTest.java
Labels: enhancement, Java, Front End, Security, Test, size:M

#3701 Update hungarian translation for teams, table of contents features, and new admin labels.
  stirling-pdf/src/main/resources/messages_hu_HU.properties
Labels: Translation, size:M

#3702 feat: add i18n support for team management UI and role table header
  proprietary/src/main/resources/static/css/modern-tables.css
  proprietary/src/main/resources/templates/accounts/team-details.html
  proprietary/src/main/resources/templates/accounts/teams.html
  scripts/ignore_translation.toml
  stirling-pdf/src/main/resources/messages_ar_AR.properties
  stirling-pdf/src/main/resources/messages_az_AZ.properties
  stirling-pdf/src/main/resources/messages_bg_BG.properties
  stirling-pdf/src/main/resources/messages_bo_CN.properties
  stirling-pdf/src/main/resources/messages_ca_CA.properties
  stirling-pdf/src/main/resources/messages_cs_CZ.properties
  stirling-pdf/src/main/resources/messages_da_DK.properties
  stirling-pdf/src/main/resources/messages_de_DE.properties
  stirling-pdf/src/main/resources/messages_el_GR.properties
  stirling-pdf/src/main/resources/messages_en_GB.properties
  stirling-pdf/src/main/resources/messages_en_US.properties
  stirling-pdf/src/main/resources/messages_es_ES.properties
  stirling-pdf/src/main/resources/messages_eu_ES.properties
  stirling-pdf/src/main/resources/messages_fa_IR.properties
  stirling-pdf/src/main/resources/messages_fr_FR.properties
  stirling-pdf/src/main/resources/messages_ga_IE.properties
  stirling-pdf/src/main/resources/messages_hi_IN.properties
  stirling-pdf/src/main/resources/messages_hr_HR.properties
  stirling-pdf/src/main/resources/messages_hu_HU.properties
  stirling-pdf/src/main/resources/messages_id_ID.properties
  stirling-pdf/src/main/resources/messages_it_IT.properties
  stirling-pdf/src/main/resources/messages_ja_JP.properties
  stirling-pdf/src/main/resources/messages_ko_KR.properties
  stirling-pdf/src/main/resources/messages_ml_IN.properties
  stirling-pdf/src/main/resources/messages_ml_ML.properties
  stirling-pdf/src/main/resources/messages_nl_NL.properties
  stirling-pdf/src/main/resources/messages_no_NB.properties
  stirling-pdf/src/main/resources/messages_pl_PL.properties
  stirling-pdf/src/main/resources/messages_pt_BR.properties
  stirling-pdf/src/main/resources/messages_pt_PT.properties
  stirling-pdf/src/main/resources/messages_ro_RO.properties
  stirling-pdf/src/main/resources/messages_ru_RU.properties
  stirling-pdf/src/main/resources/messages_sk_SK.properties
  stirling-pdf/src/main/resources/messages_sl_SI.properties
  stirling-pdf/src/main/resources/messages_sr_LATN_RS.properties
  stirling-pdf/src/main/resources/messages_sv_SE.properties
  stirling-pdf/src/main/resources/messages_th_TH.properties
  stirling-pdf/src/main/resources/messages_tr_TR.properties
  stirling-pdf/src/main/resources/messages_uk_UA.properties
  stirling-pdf/src/main/resources/messages_vi_VN.properties
  stirling-pdf/src/main/resources/messages_zh_CN.properties
  stirling-pdf/src/main/resources/messages_zh_TW.properties
  stirling-pdf/src/main/resources/templates/adminSettings.html
Labels: Documentation, enhancement, Front End, Translation, size:XL

#3712 Restore zh_TW locale to state before incorrect commit
  stirling-pdf/src/main/resources/messages_zh_TW.properties
Labels: Translation, size:M

#3649 Update and improve zh_TW Traditional Chinese locale
  stirling-pdf/src/main/resources/messages_zh_TW.properties
Labels: Translation, size:M

#3715 translate en-GB to de_DE
  stirling-pdf/src/main/resources/messages_de_DE.properties
Labels: Translation, size:S

#3724 chore: expand allowed license list with additional Eclipse Public License variants
  allowed-licenses.json
Labels: size:XS

#3719 feat: Improve team management UX with message-based feedback and internal team protection
  proprietary/src/main/java/stirling/software/proprietary/security/config/AccountWebController.java
  proprietary/src/main/java/stirling/software/proprietary/security/controller/api/TeamController.java
  proprietary/src/main/java/stirling/software/proprietary/security/controller/web/TeamWebController.java
  proprietary/src/main/resources/templates/accounts/team-details.html
  proprietary/src/main/resources/templates/accounts/teams.html
  stirling-pdf/src/main/resources/messages_en_GB.properties
  stirling-pdf/src/main/resources/templates/adminSettings.html
Labels: enhancement, Java, Front End, Translation, Security, size:L

#3717 HowToAddNewLanguage add linux command, fix md code type
  HowToAddNewLanguage.md
Labels: Documentation, size:S

#3757 Update PR-Demo-Comment-with-react.yml for security flags
  .github/workflows/PR-Demo-Comment-with-react.yml
Labels: Github, size:XS

#3739 Auditing support
  common/src/main/java/stirling/software/common/model/ApplicationProperties.java
  common/src/main/java/stirling/software/common/util/RequestUriUtils.java
  proprietary/src/main/java/stirling/software/proprietary/audit/AuditAspect.java
  proprietary/src/main/java/stirling/software/proprietary/audit/AuditEventType.java
  proprietary/src/main/java/stirling/software/proprietary/audit/AuditLevel.java
  proprietary/src/main/java/stirling/software/proprietary/audit/AuditUtils.java
  proprietary/src/main/java/stirling/software/proprietary/audit/Audited.java
  proprietary/src/main/java/stirling/software/proprietary/audit/ControllerAuditAspect.java
  proprietary/src/main/java/stirling/software/proprietary/config/AsyncConfig.java
  proprietary/src/main/java/stirling/software/proprietary/config/AuditConfigurationProperties.java
  proprietary/src/main/java/stirling/software/proprietary/config/AuditJpaConfig.java
  proprietary/src/main/java/stirling/software/proprietary/config/CustomAuditEventRepository.java
  proprietary/src/main/java/stirling/software/proprietary/config/HttpRequestAuditPublisher.java
  proprietary/src/main/java/stirling/software/proprietary/controller/AuditDashboardController.java
  proprietary/src/main/java/stirling/software/proprietary/model/security/PersistentAuditEvent.java
  proprietary/src/main/java/stirling/software/proprietary/repository/PersistentAuditEventRepository.java
  proprietary/src/main/java/stirling/software/proprietary/security/CustomAuthenticationFailureHandler.java
  proprietary/src/main/java/stirling/software/proprietary/security/CustomAuthenticationSuccessHandler.java
  proprietary/src/main/java/stirling/software/proprietary/security/CustomLogoutSuccessHandler.java
  proprietary/src/main/java/stirling/software/proprietary/security/InitialSecuritySetup.java
  proprietary/src/main/java/stirling/software/proprietary/security/config/EnterpriseEndpoint.java
  proprietary/src/main/java/stirling/software/proprietary/security/config/EnterpriseEndpointAspect.java
  proprietary/src/main/java/stirling/software/proprietary/service/AuditCleanupService.java
  proprietary/src/main/java/stirling/software/proprietary/service/AuditService.java
  proprietary/src/main/java/stirling/software/proprietary/util/SecretMasker.java
  proprietary/src/main/java/stirling/software/proprietary/web/AuditWebFilter.java
  proprietary/src/main/java/stirling/software/proprietary/web/CorrelationIdFilter.java
  proprietary/src/main/resources/application-proprietary.properties
  proprietary/src/main/resources/static/css/audit-dashboard.css
  proprietary/src/main/resources/static/js/audit/dashboard.js
  proprietary/src/main/resources/templates/AUDIT_HELP.md
  proprietary/src/main/resources/templates/AUDIT_USAGE.md
  proprietary/src/main/resources/templates/audit/dashboard.html
  stirling-pdf/src/main/java/stirling/software/SPDF/SPDFApplication.java
  stirling-pdf/src/main/java/stirling/software/SPDF/config/CleanUrlInterceptor.java
  stirling-pdf/src/main/resources/messages_en_GB.properties
  stirling-pdf/src/main/resources/settings.yml.template
  stirling-pdf/src/main/resources/templates/adminSettings.html
Labels: Documentation, enhancement, Java, Front End, Back End, Translation, Security, size:XXL

#3762 fix: ensure locale-safe formatting in GeneralUtils.formatBytes
  common/src/main/java/stirling/software/common/util/GeneralUtils.java
Labels: Bug, Java, Test, size:S

#3764 Version prop fix + test
  build.gradle
  testing/test.sh
Labels: size:M

#3763 Update messages_it_IT.properties
  stirling-pdf/src/main/resources/messages_it_IT.properties
Labels: Translation, size:L

#3776 Update multi-toolAdvert to respect SYSTEM_ROOTURIPATH.
  stirling-pdf/src/main/resources/templates/fragments/multi-toolAdvert.html
Labels: Front End, size:XS

#3768 ci: add matrix strategy for spring-security and improve test report check logic
  .github/workflows/build.yml
Labels: enhancement, Docker, Github, size:M

#3783 Improve Turkish translations for Fake Scan, TOC, and Cookie Banner
  stirling-pdf/src/main/resources/messages_tr_TR.properties
Labels: Translation, size:L

#3782 ci: add cleanup step to remove temporary files in workflow
  .github/workflows/check_properties.yml
Labels: Github, size:XS, ci

#3781 Add Attachments Feature
  common/build.gradle
  common/src/main/java/stirling/software/common/util/AttachmentUtils.java
  common/src/main/java/stirling/software/common/util/EmlToPdf.java
  common/src/main/java/stirling/software/common/util/WebResponseUtils.java
  common/src/test/java/stirling/software/common/util/WebResponseUtilsTest.java
  stirling-pdf/src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/api/MergeController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/api/misc/AttachmentController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/api/misc/BlankPageController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImagesController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/api/security/CertSignController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/web/OtherWebController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/model/api/misc/AddAttachmentRequest.java
  stirling-pdf/src/main/java/stirling/software/SPDF/service/AttachmentService.java
  stirling-pdf/src/main/java/stirling/software/SPDF/service/AttachmentServiceInterface.java
  stirling-pdf/src/main/resources/messages_en_GB.properties
  stirling-pdf/src/main/resources/static/js/file-icon-factory.js
  stirling-pdf/src/main/resources/static/js/fileInput.js
  stirling-pdf/src/main/resources/templates/fragments/common.html
  stirling-pdf/src/main/resources/templates/fragments/navElements.html
  stirling-pdf/src/main/resources/templates/home-legacy.html
  stirling-pdf/src/main/resources/templates/misc/add-attachments.html
  stirling-pdf/src/test/java/stirling/software/SPDF/controller/api/misc/AttachmentControllerTest.java
  stirling-pdf/src/test/java/stirling/software/SPDF/service/AttachmentServiceTest.java
  testing/allEndpointsRemovedSettings.yml
  testing/endpoints.txt
  testing/webpage_urls.txt
Labels: Java, Front End, Back End, Translation, API, Test, size:XL, Gradle

#3811 Stirling 2.0
  frontend/src/components/fileManagement/FileManager.tsx
  frontend/src/components/pageEditor/BulkSelectionPanel.tsx
  frontend/src/components/pageEditor/DragDropGrid.tsx
  frontend/src/components/pageEditor/FileEditor.tsx
  frontend/src/components/pageEditor/FileThumbnail.tsx
  frontend/src/components/pageEditor/PageEditor.module.css
  frontend/src/components/pageEditor/PageEditor.tsx
  frontend/src/components/pageEditor/PageEditorControls.tsx
  frontend/src/components/pageEditor/PageThumbnail.tsx
  frontend/src/components/shared/FilePickerModal.tsx
  frontend/src/components/shared/FileUploadSelector.tsx
  frontend/src/hooks/useFileWithUrl.ts
  frontend/src/hooks/useToolParams.ts
  frontend/src/pages/HomePage.tsx
Labels: size:XL

#3826 Added mockTempFileManager to tests in EML-to-PDF mockito to resolve errors
  common/src/test/java/stirling/software/common/util/EmlToPdfTest.java
Labels: Test, size:S

#3833 Feature/react backend config access
  common/src/main/java/stirling/software/common/service/TempFileCleanupService.java
  common/src/main/java/stirling/software/common/util/TempFileRegistry.java
  frontend/src/components/shared/AppConfigModal.tsx
  frontend/src/components/shared/QuickAccessBar.tsx
  frontend/src/hooks/useAppConfig.ts
  frontend/src/hooks/useEndpointConfig.ts
  frontend/src/pages/HomePage.tsx
  frontend/src/tools/Compress.tsx
  frontend/src/tools/Merge.tsx
  frontend/src/tools/Split.tsx
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/api/misc/ConfigController.java
  stirling-pdf/src/main/java/stirling/software/SPDF/controller/web/HomeWebController.java
Labels: Java, Front End, Back End, API, size:XL

#3838 refactor: replace deprecated `fields()` with `propertyStream()` in ApiDocService
  stirling-pdf/src/main/java/stirling/software/SPDF/service/ApiDocService.java
Labels: Java, API, size:XS, refactor
